### ISSUE TITLE
How to change transform(TRS) of each effect

### ISSUE THREAD

**Issue by emadurandal** [effekseer/Effekseer#100]
質問系もOKとのことなので、書き込みます。

自作WebGLライブラリのGLBoostに組み込みたいと考えていまして、今ドキュメントで仕様を確認しているのですが、setProjectionMatrixやsetCameraMatrixは見つかりましたが、各エフェクトを移動するためのsetWorldMatrix的なものが見つかりません（各モデルを動かすことを想定しているので、おそらくsetProjectionMatrixなどとは別のクラスにそうしたものがあると思っていますが）。

私の探し方が足りない場合は、ご指摘いただければ幸いです。あるいは、World行列のようなものではない仕組みでエフェクトの移動（というかトランスフォーム）を処理しているのでしょうか？

**Comment by durswd** [comment]
https://github.com/effekseer/EffekseerForWebGL/blob/master/Dev/Source/effekseer.src.js

setMatrixでエフェクトの行列を設定できます。

**Comment by emadurandal** [comment]
ありがとうございます！やってみます。
あ、クローズしていただいて結構です。
