### ISSUE TITLE
Implement in WebGL

### ISSUE THREAD

**Issue by skymen** [effekseer/Effekseer#1000]
Hi, how can I implement Effekseer for a new engine? I want to try and implement this for Construct. I know it should work on web because it mentions WebGL support and also RPG Maker uses this which I think uses web technologies.

Is there documentation on how to do that, or examples that use vanilla JS?

**Comment by durswd** [comment]
Please read this repository.

https://github.com/effekseer/EffekseerForWebGL

**Comment by skymen** [comment]
Thank you very much. I'm working on implementing this in the engine :)

I have one question though: Does this support WebGL1 AND WebGL2? Also, is WebGPU support planned or not?

Construct 3 supports all 3 and I want to know if I need to double check for rendering context before doing anything with the context C3 gives me.

**Comment by skymen** [comment]
OK thanks for the answers
