### ISSUE TITLE
Failure to run on NVIDIA Linux

### ISSUE THREAD

**Issue by Frontear** [effekseer/Effekseer#1026]
Hi! Many of our users have had an issue with their NVIDIA cards where it errors out with:

```
libEffekseerNativeForJava.so: undefined symbol: glGenSamplers
```

It seems that on NVIDIA, OpenGL 3.3+ isn't enforced, which causes a crash. Could you please look into this and let me know if there's some kind of information you'd need?

**Comment by durswd** [comment]
Please use OpenGL 2.1 version

**Comment by Frontear** [comment]
Are there any other alternatives besides using an older form of GL? All these GPUs can support OpenGL 4.6, but for some reason they do not have the proper context only when this library is introduced.

**Comment by durswd** [comment]
I don't understand why it occurs.
I only call glGenSamplers

https://github.com/effekseer/Effekseer/blob/85a25980f250f0359e6024f3c134930eef779d5f/Dev/Cpp/EffekseerRendererGL/EffekseerRendererGL/EffekseerRendererGL.GLExtension.cpp#L849

**Comment by Frontear** [comment]
A user determined that the cause may have been due to https://github.com/effekseer/EffekseerForMultiLanguages compiling without GL correctly linked. 

This was determined by user @ripjackie here: [](https://github.com/ChloePrime/AAAParticles/pull/33)

**Comment by ripjackie** [comment]
Hello! @Frontear is correct, effekseer/EffekseerForMultiLanguages was being compiled incorrectly and included in ChloePrime/AAAParticles. After rebuilding the repo the error went away.

**Comment by durswd** [comment]
I'm glad if you send PR to  https://github.com/effekseer/EffekseerForMultiLanguages

**Comment by Frontear** [comment]
Closing my issue as invalid. The issue was not due to this repo. I can confirm because I have re-compiled the library exactly as is and it works. It seems the downstream mod "AAA Particles" simply had a broken version of the library, though I do not know where they got it from.

**Comment by Frontear** [comment]
Here's my repo where I can confirm your code was not the problem: https://github.com/Frontear/effekseer-libs

Thank you for being responsive nonetheless!
