### ISSUE TITLE
wrong transformations in cocos2d-x

### ISSUE THREAD

**Issue by huachangmiao** [effekseer/Effekseer#103]
There is one major problem with the cocos2d-x integration - rendering seem to completely ignore parent transformations. What I mean is: when I add an effect as child to some cocos2d::Node and move that node, the effect doesn’t move

**Comment by durswd** [comment]
OK. I will check it. Please wait few days.

**Comment by huachangmiao** [comment]
there has another problem.
in default camera, the transformations is correct.
however, i created another camera, in this codes.

local camera = cc.Camera:createPerspective(30, MAX_SCREEN_WIDTH / MAX_SCREEN_HEIGHT, 1, 100000)

camera:setCameraFlag(cc.CameraFlag.USER1)
camera:setPosition3D(cc.vec3(90, 90, 0))
this:addChild(camera)
then

emitter:setCameraMask(cc.CameraFlag.USER1)

in this way, the transformations still wrong.
i think the m_camera and m_proj in class RendererImplemented needs to be recalculation.

the cameras in this function
void Scene::render(Renderer* renderer)

i try to fix it. this is my changes.
http://discuss.cocos2d-x.org/uploads/default/original/3X/0/9/09f5c4d8a9a5969343785fdfbf8c2c2ace11f047.zip

**Comment by durswd** [comment]
Thank you for your changes.
After check it, I will merge almost changes if it runs.
Please tell your name to publish as a contributor.

My plans and questions.

cocos2d::Director::getInstance()->getEffekseerManager();
this causes compiling error.

-EffekseerRendererNative.h EffekseerRendererNative.cpp
This is an auto generated code. So I add a callback to get draw call

-namespace
Sorry for I don't merge it. Because Effect is very common class name.
When an user define using namespace cocos2d, it possible to conflict it.

**Comment by durswd** [comment]
I changed and merged.
https://github.com/effekseer/EffekseerForCocos2d-x

**Comment by huachangmiao** [comment]
thanks for your feedback.
- cocos2d::Director::getInstance()->getEffekseerManager();
i using EffekseerManager class with singleton mode in my project, and it's not important.
i merged your update. and overload create function and constructed function.

-EffekseerRendererNative.h EffekseerRendererNative.cpp
-namespace
Good advice！

it's running normally when i update your code.
thank you very much.

**Comment by durswd** [comment]
@huachangmiao 
May I revert a transform function?

from 
manager->setMatrix(handle, _modelViewTransform);

to
auto transform = this->getNodeToWorldTransform();
manager->setMatrix(handle, transform);

Because  _modelViewTransform is not calculated in onEnter
so first frame is wrong.

**Comment by huachangmiao** [comment]
there are two place call this function.
do you mean revert all of them or just revert it in play function?

**Comment by durswd** [comment]
I think i revert two place. Because the change of position, rotation and scale delays 1 frame to apply to effects

**Comment by huachangmiao** [comment]
ok, i got it.

**Comment by durswd** [comment]
Thank you for your reply

**Comment by durswd** [comment]
I fixed it
https://github.com/effekseer/EffekseerForCocos2d-x/commit/46fb9a586d6133522fb1fd928e1df27c9c0453c7

**Comment by huachangmiao** [comment]
it's OK.
