### ISSUE TITLE
distortion is invalid (cocos2d-x)

### ISSUE THREAD

**Issue by huachangmiao** [effekseer/Effekseer#104]
https://github.com/effekseer/EffekseerForCocos2d-x/issues/3

**Comment by durswd** [comment]
I will check after a few days

**Comment by durswd** [comment]
I found that a distortion is wrong.
I'll fix it

**Comment by durswd** [comment]
You perhaps need this code.
```
manager->setIsDistortionEnabled(true);
```

![image](https://user-images.githubusercontent.com/5775729/38430970-ca1f9abe-39fd-11e8-9196-b99328fe6a2a.png)

**Comment by huachangmiao** [comment]
The effect is not so obvious in cocos2d-x.

**Comment by durswd** [comment]
I think it too.
I seem that i need to add a function to increase an intensity of distortion.

**Comment by huachangmiao** [comment]
![egk55l l__z 3i ts ib457](https://user-images.githubusercontent.com/26161671/38455232-d1baf2fa-3aa7-11e8-8ab3-60c43f185d90.png)

**Comment by durswd** [comment]
It seem the intensity is different.
I'll fix it

**Comment by huachangmiao** [comment]
yep. 
It seem 50 times the difference.
I scale the intensity to 50.0f. It's looks ok.
<img width="239" alt="84c3cba2d5012f95c4e9bc900be9dfa3" src="https://user-images.githubusercontent.com/26161671/38455607-1c776332-3aad-11e8-9071-882172d3d7d7.png">

**Comment by durswd** [comment]
I found that distortion intensity is not scaled.
If you'd like to distort as same as an editor, you cannot scale this effect.
I'll fix it or add new options.
