### ISSUE TITLE
suggest the transformations still update when it is pause (cocos2d-x)

### ISSUE THREAD

**Issue by huachangmiao** [effekseer/Effekseer#105]
void ManagerImplemented::UpdateHandle( DrawSet& drawSet, float deltaFrame )
{
	float df = drawSet.IsPaused ? 0 : deltaFrame * drawSet.Speed;
	drawSet.InstanceContainerPointer->Update( true, df, drawSet.IsShown );
	if( drawSet.DoUseBaseMatrix )
	{
		drawSet.InstanceContainerPointer->SetBaseMatrix( true, drawSet.BaseMatrix );
	}
	drawSet.GlobalPointer->AddUpdatedFrame( df );
}

Can I make this change?

**Comment by durswd** [comment]
Thank you, If you cannot, I try it.

**Comment by huachangmiao** [comment]
before i changed
![6](https://user-images.githubusercontent.com/26161671/38287436-3a33c238-37fd-11e8-8e4b-01edd61680ea.gif)
after i changed
![5](https://user-images.githubusercontent.com/26161671/38287435-39e58262-37fd-11e8-9d81-90919f79d9fa.gif)

**Comment by durswd** [comment]
Good!

**Comment by durswd** [comment]
Should I apply it or do you send a pull request?

**Comment by huachangmiao** [comment]
i just change my code follow my fisrt message in this issue.
do you think is ok?

**Comment by durswd** [comment]
OK

**Comment by durswd** [comment]
I fixed it
https://github.com/effekseer/EffekseerForCocos2d-x/commit/46fb9a586d6133522fb1fd928e1df27c9c0453c7

**Comment by huachangmiao** [comment]
it's OK.
