### ISSUE TITLE
ios make error(cocos2d-x)

### ISSUE THREAD

**Issue by widwei** [effekseer/Effekseer#107]
in xcode Uknow type name '_m128’ in EffekseerNative.cpp :2903
i think you need add code:
#ifdef _sse_
#include <xmmintrin.h>
#endif

**Comment by durswd** [comment]
I tried to fix it.
Please check it.
https://github.com/effekseer/EffekseerForCocos2d-x/commit/5ab09a4a377c91b92abf9edb40d78d003b38e41a

**Comment by widwei** [comment]
it's ok
