### ISSUE TITLE
RenderingPriority in class EffectNodeImplemented not initialize (cocos2d-x ios)

### ISSUE THREAD

**Issue by huachangmiao** [effekseer/Effekseer#108]
variable RenderingPriority' s default value is a random value in win32 debug
however in ios default value is zero.

InstanceContainer::InstanceContainer( Manager* pManager, EffectNode* pEffectNode, InstanceGlobal* pGlobal, int ChildrenCount )
	: m_pManager		( pManager )
	, m_pEffectNode((EffectNodeImplemented*) pEffectNode)
	, m_pGlobal			(pGlobal)
	, m_Children		( NULL )
	, m_ChildrenCount	( ChildrenCount )
	, m_headGroups		( NULL )
	, m_tailGroups		( NULL )

{
	auto en = (EffectNodeImplemented*)pEffectNode;
	if (en->RenderingPriority >= 0)
	{
		**# pGlobal->RenderedInstanceContainers[en->RenderingPriority] = this;**
	}

	m_Children = (InstanceContainer**)m_pManager->GetMallocFunc()( sizeof(InstanceContainer*) * m_ChildrenCount );
	for( int i = 0; i < m_ChildrenCount; i++ )
	{
		m_Children[ i ] = NULL;
	}
}

it' s will crash in this line 
pGlobal->RenderedInstanceContainers[en->RenderingPriority] = this;

suggest set RenderingPriority's default value to -1.

**Comment by durswd** [comment]
I fixed it.

https://github.com/effekseer/Effekseer/commit/2358425fb985e45863db3aec7b45697e9863d733

https://github.com/effekseer/EffekseerForCocos2d-x/commit/4144b29c7e4a9c0a25ff0d6130576609a6f505cf

**Comment by huachangmiao** [comment]
it's ok
