### ISSUE TITLE
The effect of the game is not consistent with the editor

### ISSUE THREAD

**Issue by lishunan12351** [effekseer/Effekseer#111]
in the editor
![aaf](https://user-images.githubusercontent.com/15611020/38921495-81d2ea70-4328-11e8-8f8a-57b1561a6ba7.gif)
in game
![aag](https://user-images.githubusercontent.com/15611020/38921549-a26c010e-4328-11e8-95ea-2b87b281364b.gif)
Do I need to check where?

**Comment by huachangmiao** [comment]
InstanceGlobal* instanceGlobal = m_pContainer->GetRootInstance();

		float force = m_pEffectNode->LocationAbs.attractiveForce.force;
		float control = m_pEffectNode->LocationAbs.attractiveForce.control;
		float minRange = m_pEffectNode->LocationAbs.attractiveForce.minRange;
		float maxRange = m_pEffectNode->LocationAbs.attractiveForce.maxRange;
		
		Vector3D position = m_GlobalPosition - m_GlobalVelocity + m_GlobalRevisionLocation;

mabey thie position is wrong

**Comment by durswd** [comment]
I'm sorry for lack of function.
I added a function to get internal handle.

https://github.com/effekseer/EffekseerForCocos2d-x

This code sets position into an emitter.
```
this->manager->getInternalManager()->SetTargetLocation(emitter->getInternalHandle(), Effekseer::Vector3D(0, 5, 0));
```
![image](https://user-images.githubusercontent.com/5775729/38929611-d9b2011c-4347-11e8-826f-c149b4e646c5.png)

**Comment by huachangmiao** [comment]
I will try. thank you.

**Comment by lishunan12351** [comment]
hello,were should i add this code?
this->manager->getInternalManager()->SetTargetLocation(emitter->getInternalHandle(), Effekseer::Vector3D(0, 5, 0));
and the second parameter，Shouldn't it be specified in the editor? @durswd

**Comment by huachangmiao** [comment]
The track of motion has changed when I scale the emitter.
scale 1.0f
![0001](https://user-images.githubusercontent.com/26161671/38970842-5a0b40ee-43ca-11e8-94fc-35553c5861f3.gif)
scale 5.0f
![0002](https://user-images.githubusercontent.com/26161671/38970843-5b2ac1d4-43ca-11e8-86d2-48e0e25354eb.gif)
scale 10.0f
![0003](https://user-images.githubusercontent.com/26161671/38970845-5e229b78-43ca-11e8-9866-88a0310dcb52.gif)

How can I get the same trace motion when I scale the emitter？
the emitter is too small in my game.

**Comment by durswd** [comment]
Please change these values.
If you multiple emitter by 5, the values should be multiplied by 5.

![image](https://user-images.githubusercontent.com/5775729/38990804-9e39c62c-4416-11e8-9abc-3c14a3310ce6.png)

**Comment by durswd** [comment]
I think it is bug.

**Comment by durswd** [comment]
I fixed this bug on this branch.

https://github.com/effekseer/EffekseerForCocos2d-x/tree/optimized

**Comment by huachangmiao** [comment]
setScale(1.0)  with setTargetLocation(0, 10, 0)  
![0001](https://user-images.githubusercontent.com/26161671/39110039-25ac40a6-4702-11e8-8079-da72911720c7.gif)
 setScale(5.0)  with setTargetLocation(0, 50, 0)  
![0002](https://user-images.githubusercontent.com/26161671/39110041-27606148-4702-11e8-89c8-a231e949c2d8.gif)
Do I still need to adjust anything?

**Comment by durswd** [comment]
You need to magnify an effect when .efk is exported from Effekseer.
But it is troublesome. So I added a function to specify magnification rate when .efk is loaded.

https://github.com/effekseer/EffekseerForCocos2d-x/tree/optimized

```
auto effect = efk::Effect::create("Homing_Laser01.efk", 5);
```

5 is magnification rate
