### ISSUE TITLE
When I rotate Emitter, targetLocation will not change.

### ISSUE THREAD

**Issue by lishunan12351** [effekseer/Effekseer#112]
![aag](https://user-images.githubusercontent.com/15611020/38988261-29dd3f4a-4405-11e8-9878-f7ef84a6fc9f.gif)

**Comment by lishunan12351** [comment]
I should be able to reset locationPosition, but I can't compute the correct position.

**Comment by durswd** [comment]
Even if you rotate an emitter, a target position is not rotated. A target position is absolute position in the world.
You need to calculate absolute position based on emitter's matrix.

**Comment by durswd** [comment]
for example,

emitter->getPosition3D() + emitter->getNodeToWorldTransform().getUpVector() * xxx;

**Comment by lishunan12351** [comment]
Thank you. I've solved it.

**Comment by lishunan12351** [comment]
There is another question, can I get the value set in the editor? so that i can set default value of the targetLocation.

**Comment by durswd** [comment]
Current version doesn't have a this method.
