### ISSUE TITLE
built failed in android (branch optimized)

### ISSUE THREAD

**Issue by huachangmiao** [effekseer/Effekseer#113]
![h5 0c 2eyfv qnntl9gl 8](https://user-images.githubusercontent.com/26161671/39241402-57f5649e-48b9-11e8-88c9-7cd8b6819025.jpg)

**Comment by durswd** [comment]
Because I hasn't check on Android yet.
I'll check it on weekend.

**Comment by durswd** [comment]
at least, I fixed compiled bug(typo).
And I'm going to run it.

**Comment by durswd** [comment]
Current progress
I found that it is slow on Android.
To solve this,

1. Use OpenGL ES 3.0 (I think it is easy and I need to implement openGL ES3.0 option)
2. Use OpenGL ES 2.0 Extension (But I found that segmentation fault is caused on Huwei's smatphone)
3. Implementing double or triple buffering

I try to 3.

**Comment by durswd** [comment]
It can compile on Android
