### ISSUE TITLE
Compile on Mac

### ISSUE THREAD

**Issue by klnvnv** [effekseer/Effekseer#115]
Hey guys, I see there's the MultiPlatform stuff, but I don't know how to build it on a Mac.
I'm thinking that I need to use mono for this, but I'm guessing at what I should do.

I installed mono and mono-libgdiplus from homebrew and ran 
xbuild /p:Configuration=Release /p:Platform=x86 Dev/Editor/EffekseerMP/EffekseerMP.csproj`
but I get these errors:

	Script/Compiler.cs(11,12): error CS0246: The type or namespace name 'IronPython' could not be found (are you missing a using directive or an assembly reference?)
	Script/Compiler.cs(10,12): error CS0246: The type or namespace name 'IronPython' could not be found (are you missing a using directive or an assembly reference?)
	Script/Compiler.cs(9,22): error CS0234: The type or namespace name 'Scripting' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

So, does the editor actually work on macOS?
The build fails here because of missing IronPython, but building IronPython fails too. Is it worth for me to try to resolve that or maybe it isn't ready yet?

**Comment by durswd** [comment]
I compile Effekseer.sln with Visual Studio for mac. I don't try xbuild
In this way, I removed View, Effekseer, EffekseerForDX9, and EffekseerForGL from Effekseer.sln

And View.dll is compiled with cmake and xcode.

Effekseer for mac has many bugs because of underdeveloping.

**Comment by klnvnv** [comment]
@durswd 
Thanks man,
I started downloading Visual Studio for Mac, and I will try it.
But, is it usable to actually create effects on a mac, or should I just run it in a windows VM maybe?

**Comment by durswd** [comment]
I think it is difficult now.
But I think I can realize it if I fix few bugs (It is required two or three holiday or week ends.)

**Comment by klnvnv** [comment]
no worries man,
so a Windows VM, would that work? I'm not sure how the GL stuff will be handled if I run it in VirtualBox on my MacBook Pro, is it gonna use a the software GL, can it run with a software GL?
Have you tried?

**Comment by durswd** [comment]
On Mac, save and load dialog are something wrong. You can make a particle effect.
(It is few days ago, I don't check the newest version.)

I haven't try it. 
I think that if games with DirectX9 run, Effekseer can be run.

**Comment by klnvnv** [comment]
@durswd 
ok thanks for the info

btw, it seems to be running ok with virtualbox under windows 10, I touched the VM settings, but I'm not sure that's needed

**Comment by durswd** [comment]
Additional information
To compile a viewer, -DBUILD_VIEWER is required in cmake

**Comment by durswd** [comment]
In the newest version, it cannot run. I need to fix it.

**Comment by durswd** [comment]
The newest version can be compiled and run on Mac

**Comment by klnvnv** [comment]
@durswd 
Thanks man

I get this error tho:
`/Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(3006,5): error MSB3554: Cannot write to the output file "/Volumes/MAIN/Users/k/Documents/sources/graphics/Effekseer/Dev/Editor/EffekseerCore/obj/x86/Debug/Effekseer.Properties.Resources.resources". A null reference or invalid value was found [GDI+ status: InvalidParameter]`

**Comment by durswd** [comment]
I don't understand why these errors are caused. But Resources.resx has not used EffekseerMP, so we can remove it.

**Comment by durswd** [comment]
In japan. It is night and I 'm going to sleep. I'll remove it tomorrow.

**Comment by klnvnv** [comment]
yep,
I wasn't using git-lfs; now I do have those .dlls in the tree and I do get further, but there's other stuff now.

So, this is the stuff I do:
I open Effekseer.sln,
remove the targets(or whatever they are called) you mention from it, and
build EffekseerMP.
EffekseerMP builds it's targets, and I see some dlls and stuff gets created in the release dir, but
VS spews out some errors that "this project type is not supported by Visual Studio Community 2017 for Mac" and that's it, but it does build some .dlls
<img width="1831" alt="screen shot 2018-05-10 at 10 36 19" src="https://user-images.githubusercontent.com/2305662/39860262-5ee6df02-5445-11e8-9156-957668f95a0a.png">

I open EffekseerMP/EffekseerMP.csproj and I build it. The build actually goes ok (if I only open EffekseerMP.csproj on a clean project, before building Effekseer.sln, it complains that a dll is missing)
So, the build went ok and VS tries to launch the app, but it throws an exception on line 43 in swig/GUIManager.cs and exits.
<img width="1829" alt="screen shot 2018-05-10 at 11 27 15" src="https://user-images.githubusercontent.com/2305662/39860274-6a9e8246-5445-11e8-8426-de89e80c28ff.png">

I think it might be trying to import a dll named Viewer, but I'm not sure.

**Comment by durswd** [comment]
Does libViewer.dylib exists? It need to build with cmake and copy dylib.
In addition, VisualStudio for mac's current directory is on project directory.
So You need to run with mono EffekseerMP.exe.

**Comment by klnvnv** [comment]
nope, I don't have libViewer.dylib, I tried compiling it with the cmake generated Xcode project, but I get errors. I tried tweaking the build settings but new stuff keeps popping up.

I'm giving up for now and I'll just use the editor in a VM under Windows.

If you're going to dig in to it further, you can message me and I can try stuff out if you want.

**Comment by durswd** [comment]
I'm sorry. It is difficult to compile this code because of developing.
Please wait to provide prebuild binaries.

**Comment by durswd** [comment]
I finished to create app.

https://github.com/effekseer/Effekseer/releases/download/NightlyBuild/EffekseerForMac_0520.zip

But it has many bugs.
I recommend you to continue to use Effekseer 1.30 on VM.

**Comment by klnvnv** [comment]
Thanks for all the hard work!
