### ISSUE TITLE
Compile on Linux

### ISSUE THREAD

**Issue by v1993** [effekseer/Effekseer#116]
I try to compile on linux. However, `python3 Script/build_libgd.py` fails with message about missing `gd_bin/Bin/libgd.a`.

After checking that directory I discovered that dynamic library (`libgd.so`) has been built instead of static ine (`libgd.a`).

How can I fix it?

**Comment by durswd** [comment]
I fixed build_libgd.py
But I 'm not sure that it succeed.
I'm focusing for MacOSX.

I think almost process is same as mac.

https://github.com/effekseer/Effekseer/issues/115

**Comment by v1993** [comment]
New problem:

    libgd_cp/src/gd_color_map.h :       ../Dev/Cpp/include/gd/gd_color_map.h
    libgd_cp/src/entities.h     :       ../Dev/Cpp/include/gd/entities.h
    libgd_cp/src/gdfonts.h      :       ../Dev/Cpp/include/gd/gdfonts.h
    libgd_cp/src/gdcache.h      :       ../Dev/Cpp/include/gd/gdcache.h
    libgd_cp/src/gdfontl.h      :       ../Dev/Cpp/include/gd/gdfontl.h
    libgd_cp/src/gdpp.h :       ../Dev/Cpp/include/gd/gdpp.h
    libgd_cp/src/gdhelpers.h    :       ../Dev/Cpp/include/gd/gdhelpers.h
    libgd_cp/src/gd_errors.h    :       ../Dev/Cpp/include/gd/gd_errors.h
    libgd_cp/src/gdfontt.h      :       ../Dev/Cpp/include/gd/gdfontt.h
    libgd_cp/src/bmp.h  :       ../Dev/Cpp/include/gd/bmp.h
    libgd_cp/src/jisx0208.h     :       ../Dev/Cpp/include/gd/jisx0208.h
    libgd_cp/src/gd.h   :       ../Dev/Cpp/include/gd/gd.h
    libgd_cp/src/gd_color.h     :       ../Dev/Cpp/include/gd/gd_color.h
    libgd_cp/src/config.h       :       ../Dev/Cpp/include/gd/config.h
    libgd_cp/src/gd_io_stream.h :       ../Dev/Cpp/include/gd/gd_io_stream.h
    libgd_cp/src/wbmp.h :       ../Dev/Cpp/include/gd/wbmp.h
    libgd_cp/src/gdfx.h :       ../Dev/Cpp/include/gd/gdfx.h
    libgd_cp/src/gdfontg.h      :       ../Dev/Cpp/include/gd/gdfontg.h
    libgd_cp/src/msinttypes/stdint.h    :       ../Dev/Cpp/include/gd/msinttypes/stdint.h
    libgd_cp/src/msinttypes/inttypes.h  :       ../Dev/Cpp/include/gd/msinttypes/inttypes.h
    libgd_cp/src/gdfontmb.h     :       ../Dev/Cpp/include/gd/gdfontmb.h
    libgd_cp/src/gd_tga.h       :       ../Dev/Cpp/include/gd/gd_tga.h
    libgd_cp/src/gd_nnquant.h   :       ../Dev/Cpp/include/gd/gd_nnquant.h
    libgd_cp/src/gd_intern.h    :       ../Dev/Cpp/include/gd/gd_intern.h
    libgd_cp/src/gd_io.h        :       ../Dev/Cpp/include/gd/gd_io.h
    copying from gd_bin/Bin/libgd.a to ../Dev/Cpp/lib/
    Traceback (most recent call last):
      File "Script/build_libgd.py", line 59, in <module>
        aceutils.copy(r'gd_bin/Bin/libgd.a', r'../Dev/Cpp/lib/')
      File "/home/v/compile/Effekseer/Script/aceutils.py", line 114, in copy
        shutil.copy(src,dst)
      File "/usr/lib/python3.5/shutil.py", line 235, in copy
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "/usr/lib/python3.5/shutil.py", line 115, in copyfile
        with open(dst, 'wb') as fdst:
    IsADirectoryError: [Errno 21] Is a directory: '../Dev/Cpp/lib/'

**Comment by durswd** [comment]
OK. I think that shutil.copy cannot get directory path as args on linux.
I'll fix after implementing for Mac or please fix yourself.

```
def copy(src,dst):
	print("copying from {0} to {1}".format(src, dst))
	shutil.copy(src,dst)
```
in aceutils.py
It is something wrong.
But I don't have a linux environment. So I cannot check it immediately.

**Comment by v1993** [comment]
You can check https://stackoverflow.com/q/1868714/5697743 for solution (I don't know python and can't repair things by myself).

**Comment by durswd** [comment]
Current progress : 
I finished to compile a native part.
But it required to compile a .net part.

https://github.com/effekseer/Effekseer/blob/master/README.md

**Comment by durswd** [comment]
@v1993 
I finished to compile all projects.
But I haven't debug yet. Because I compile on Bash on Windows(CUI only)
