### ISSUE TITLE
Alpha Premultiplied question

### ISSUE THREAD

**Issue by lishunan12351** [effekseer/Effekseer#118]
there is a question,texture in cocos2d is all hasPremultipliedAlpha

how should i change this code?
![ccc](https://user-images.githubusercontent.com/15611020/40606468-06e26fea-6298-11e8-8e8c-524a0cf3fc28.png)

**Comment by lishunan12351** [comment]
in editer
![11](https://user-images.githubusercontent.com/15611020/40607333-c38a23ac-629a-11e8-9a88-57e67c07ed1d.png)

in cocos
![22](https://user-images.githubusercontent.com/15611020/40607337-c9b1c924-629a-11e8-8012-9aa825770a28.png)

**Comment by huachangmiao** [comment]
in cocos

in Blend type:
if we use the texture with PremultipliedAlpha.
- glBlendFunc(GL_ONE, GL_ONE_MINUS_SRC_ALPHA)

if the texture without PremultipliedAlpha.
- glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)

in Add mode:
if we use the texture with PremultipliedAlpha.
- glBlendFunc(GL_ONE, GL_ONE)

if the texture without PremultipliedAlpha.
- glBlendFunc(GL_SRC_ALPHA, GL_ONE)

in effekseer's code:
if( m_next.AlphaBlend == ::Effekseer::AlphaBlendType::Blend )
{
	GLExt::glBlendFuncSeparate(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, GL_ONE, GL_ONE); <=
}
else if( m_next.AlphaBlend == ::Effekseer::AlphaBlendType::Add )
{
	GLExt::glBlendFuncSeparate(GL_SRC_ALPHA, GL_ONE, GL_ONE, GL_ONE); <=
}

if we use the texture with PremultipliedAlpha.
how to change the code?
