### ISSUE TITLE
a crash bug when unsurrpoted mapBuffer on some android devices.

### ISSUE THREAD

**Issue by huachangmiao** [effekseer/Effekseer#120]
It 's crash when I play effect in NUBIA NX507J

{
	cocos2d.x.version:+cocos2d-x-3.10
	cocos2d.x.compiled_with_gl_state_cache:+true
	gl.supports_S3TC:+false
	cocos2d.x.build_type:+RELEASE
	gl.supports_vertex_array_object:+true
	cocos2d.x.compiled_with_profiler:+false
	gl.renderer:+Adreno+(TM)+330
	gl.vendor:+Qualcomm
	gl.version:+OpenGL+ES+3.0+V@66.0+AU@++(CL@)
	gl.supports_ATITC:+true
	gl.supports_ETC1:+true
	gl.supports_OES_packed_depth_stencil:+true
	gl.max_texture_units:+32
	gl.supports_PVRTC:+false
	gl.max_texture_size:+4096
	gl.supports_NPOT:+true
	**gl.supports_OES_map_buffer:+false**
	gl.supports_OES_depth24:+true
	gl.supports_discard_framebuffer:+true
	gl.supports_BGRA8888:+false
}
I think this device unsupports OES_map_buffer.

Crash in this line.
![image](https://user-images.githubusercontent.com/26161671/40712669-d08a617e-6430-11e8-8442-6fcb13385d5e.png)

in cocos, they use this to check it.
_glExtensions = (char *)glGetString(GL_EXTENSIONS);

bool Configuration::checkForGLExtension(const std::string &searchName) const
{
return (_glExtensions && strstr(_glExtensions, searchName.c_str() ) ) ? true : false;
}

_supportsOESMapBuffer = checkForGLExtension("GL_OES_mapbuffer");

I fixed in https://github.com/effekseer/Effekseer/pull/119

**Comment by durswd** [comment]
Merged
