### ISSUE TITLE
the effect of the game is not consistent with the editor

### ISSUE THREAD

**Issue by lishunan12351** [effekseer/Effekseer#121]
in editer
![aa1](https://user-images.githubusercontent.com/15611020/40771960-55a32042-64f1-11e8-8cb8-555af490e4e5.png)

in cocos
![aa2](https://user-images.githubusercontent.com/15611020/40771977-5f61c480-64f1-11e8-896d-020eaee98bff.png)

project
[test.zip](https://github.com/effekseer/Effekseer/files/2057436/test.zip)

**Comment by durswd** [comment]
I cannot reproduce it.
But it causes because the texture is gray scale.

**Comment by lishunan12351** [comment]
you mean i can’t use gray scale texture?

**Comment by durswd** [comment]
Yes
