### ISSUE TITLE
投稿エフェクトの使用について

### ISSUE THREAD

**Issue by wahiko94** [effekseer/Effekseer#123]
Effekseerを利用させていただいております、和彦と申します。
DXライブラリで3Dエフェクトを扱うことが出来、ゲーム開発に役立っております。
またフォーラムでも技術的な質問に回答していただき大変助かっております。

Effekseerの使用について質問がございます。
ユーザ様が投稿された投稿エフェクトを自作のゲームに使用し
イベントにて有料で頒布したいと考えております。
（頒布時は自作ゲームのスタッフロール、readmeにEffekseerと投稿者の名前を記載させていただきます）
つきましては投稿エフェクトを商用でも使用させていただくことは可能でしょうか。

投稿エフェクトをＣＣ－０ライセンスで配布しているとのことですが
サイトの「CC-0について」のリンクが外れておりましたので、念のため
確認させていただきました、よろしくお願いいたします。

**Comment by effekseer** [comment]
Effekseerです。
返答が遅れて申し訳ございません。

大丈夫です。
リンクについて連絡もありがとうございます。
修正させていただきます。


2018年6月16日 17:03 wahiko94 <notifications@github.com>:
