### ISSUE TITLE
crash in iOS cocos2dx

### ISSUE THREAD

**Issue by huachangmiao** [effekseer/Effekseer#127]
in iOS.
crash in follow lines.
auto target = (uint8_t*)GLExt::glMapBuffer(GL_ARRAY_BUFFER, GL_WRITE_ONLY);

**Comment by huachangmiao** [comment]
compile failed in this line.
g_glUnmapBuffer = ::glUnmapBuffer;

**Comment by durswd** [comment]
I'm sorry for this bug.
I think that this bug is caused when I fixed other bugs.
I fix it at this week end.

**Comment by huachangmiao** [comment]
in windows, It's running well.

**Comment by durswd** [comment]
I fixed and checked it on iOS and Mac.

https://github.com/effekseer/EffekseerForCocos2d-x

**Comment by durswd** [comment]
I have not checked a performance yet in this version. I will try it

**Comment by durswd** [comment]
I checked a performance. I think that it is no problem

**Comment by huachangmiao** [comment]
I tested it. It 's no problems.
Thank you.
I closed this issue.
