### ISSUE TITLE
When efk is exported, dependent resource path has "../xxx/xxx.xx"

### ISSUE THREAD

**Issue by yika-aixi** [effekseer/Effekseer#132]
This can't be used in unity

![image](https://user-images.githubusercontent.com/22412994/47714241-4fa17380-dc77-11e8-81f8-224908324808.png)

![image](https://user-images.githubusercontent.com/22412994/47714267-63e57080-dc77-11e8-847b-eeb506a797a1.png)

**Comment by durswd** [comment]
Thank you for your issue.
We will fix it at this weekend or next weekend.

**Comment by yika-aixi** [comment]
You're welcome. 
Can you add an asynchronous loading mode?
Why unity Can't be change effect Rotate?

**Comment by durswd** [comment]
I need to think and research about it.

**Comment by durswd** [comment]
This bug is perhaps fixed in this commit.

https://github.com/effekseer/EffekseerForUnity/commit/c37a3a1835be9a09531e6f87d392dc351763a5a1

**Comment by yika-aixi** [comment]
ok

**Comment by durswd** [comment]
Thank you for your close.

By the way, contributor Ueshita said that async load is supported in developing EffekseerForUnity Renewal version.
(I don't know a detail and no help currently)

https://github.com/effekseer/EffekseerForUnity/tree/renewal 

this is not compatible to current version. But many points are improved.
