### ISSUE TITLE
.efkmodel File is much bigger than .c3b file or .FBX file

### ISSUE THREAD

**Issue by ofchenbin** [effekseer/Effekseer#133]
I have an 326KB .FBX file which contains model and animation, after convert to .efkmodel file, the .efkmodel file is 5.11MB. 
If convert to .c3b file, it's 155KB.
So is there anything I can do to make the .efkmodel file smaller?

**Comment by durswd** [comment]
Because Effekseer in this version converts fbx into static meshes
So to reduce bones doesn't make sense.
To reduce size, reduce the number of vertex or animation length

**Comment by ofchenbin** [comment]
> Because Effekseer in this version converts fbx into static meshes
> So to reduce bones doesn't make sense.
> To reduce size, reduce the number of vertex or animation length

Thanks for answer my question! And I still got one more, if I try to use .c3b instead, I mean modify code myself, will it work well with other nodes? I haven't read all the efk::Model code yet.

**Comment by durswd** [comment]
If you can, you should add new node.

If there are many requests to reduce or new contributor, it can reduce it.

**Comment by ofchenbin** [comment]
Thanks ,I'll see what i can do
I am using Effekseer in my game,and i think it's cool, Effekseer helps a lot, so thanks again!
