### ISSUE TITLE
In aura.efkproj "Needle" is bugged with translated to somewhere else than 0,0,0

### ISSUE THREAD

**Issue by Sandurr** [effekseer/Effekseer#139]
Regarding the sample project "\Sample\01_Suzuki01\001_magma_effect\aura.efkproj":

The "Needle" particles are bugged if the effect is positioned anywhere else but 0,0,0. It first bugs in appearance and in higher xyz values it just disappears.

Such that "g_manager->Play( g_effect, 100, 100, 100 )" causes needle particles to not be seen.

I do not know why this happens because I'm not very familiar with this library yet. From a little bit of research I did notice that "m_GlobalMatrix43" translation values turn into "NaN" at some point.

Thank you :)

Version: 1.43b
Direct3D 9   (RuntimeSample DirectX9 modified to load aura.efk will have this bug)

**Comment by durswd** [comment]
Thank you for your information.
I will check it in a few days.

**Comment by durswd** [comment]
I fixed it.
And you need to change this parameter, where particles are attracted.

![image](https://user-images.githubusercontent.com/5775729/55970911-713d6700-5cbb-11e9-85d2-3e1c292435f3.png)

master

https://github.com/effekseer/Effekseer/commit/8c132b9f72f314b1f0d08c0cdddfc4dca309f761

1.4x

https://github.com/effekseer/Effekseer/commit/8d41062dd9beaf252823f28d36feda2576a4e98f

**Comment by Sandurr** [comment]
Right, Effekseer::Manager::SetTargetLocation() works too.

**Comment by durswd** [comment]
I found other bugs and fixed it.

https://github.com/effekseer/Effekseer/releases/download/NightlyBuild/Effekseer20190415.zip
