### ISSUE TITLE
Loop animation

### ISSUE THREAD

**Issue by zoltan-mihalyi** [effekseer/Effekseer#140]
In TimelineFX Editor, there is a "loop animation" checkbox, which causes perfect animation loops.
A similar option could come in handy in Effekseer.
I don't know, how that works. Maybe it overlaps two copies of the animation.

**Comment by durswd** [comment]
Thank you for your information.
Looping animation can be realized in handly. (Please read TIPS in reference)
I need to use Timeline FX Editor.

**Comment by zoltan-mihalyi** [comment]
I couldn't find anything about this in the TIPS section
I figured out more details (suppose it is a fire effect, particles are created and they move upwards. The animation length is 30 frames): 
We should create particles in the first 30 frame. Particles living after that should be shifted by 30. For example: a particle in the 42. frame should be moved to the 12. A particle in the 63. frame should be moved to the 3.
Summed up, the particles in the X-th frame should be moved to the (X mod L)-th frame, where L is the length of the animation

**Comment by durswd** [comment]
https://effekseer.github.io/Help_Tool/index_en.html

**Comment by zoltan-mihalyi** [comment]
I have found and read the tips, but nothing about this problem.

**Comment by durswd** [comment]
OK.
You mean that there is an animation with 30 frame.
Particle 42th frame, Animation 12th frame.
Particle 62th frame, Animation 2nd frame.

1. if you have a animation as a sprite sheet.

you change a Loop and Frame Length in BasicRenderSettings.
![image](https://user-images.githubusercontent.com/5775729/55893376-18a29700-5bf3-11e9-8be8-3e5fbfe982c7.png)

2. You don't have a animation as a sprite sheet.

- Parent node
You change SpwnCount, Time to live and Spawn rate.

![image](https://user-images.githubusercontent.com/5775729/55893527-60c1b980-5bf3-11e9-86d6-a2ce71678afe.png)

- Child node
You check Destroy with parent.

![image](https://user-images.githubusercontent.com/5775729/55893598-8e0e6780-5bf3-11e9-8ee9-9855f2c2ef39.png)

**Comment by zoltan-mihalyi** [comment]
Thanks for your help, but unfortunately, this isn't the soultion for my problem (as far as I see).
I was a bit unclear. I need to export the animation as a 2d sprite sheet, and the exported animation should be loopable.
The problem comes with the randomness of particles. Making a perfectly loopable fire animation seems to be impossible to me.

The solution: the paricles should not die when jumping back to frame 1.
Assume the particle time-to-live is 10. For example, in frame 3, the particle created in the 1. frame is still living. But the particle created in the 29. frame should also live (and should be destroyed in the 9. frame)!
So the particles should be displayed 'before' they are created.

Right now is solve the problem after I export the sprite sheet: 
40 frames are exported: 1-30: generate particles, 31-40: waiting for remaining particles to be destroyed
Then I edit the exported animation and blend the frames 31-40 to 1-10 (using 'add' blend mode).
This causes a perfect loop (1-30), but has some limitations:
- cannot use z-index
- cannot use different blend modes for different particles
- manual work

**Comment by durswd** [comment]
OK! I understood. I think that I realize to export lopping 2d sprite sheet.
But I need to add new functions.
I will implement these functions in this weekend. Is it OK?

**Comment by durswd** [comment]
OK! I understood. I think that I realize to export lopping 2d sprite sheet.
But I need to add new functions.
I will implement these functions in this weekend. Is it OK?

**Comment by zoltan-mihalyi** [comment]
Thank you very much! I can create effects and export them later :)
Timeline FX "Loop Animation" feature:
https://youtu.be/I0qEip5D-XA?t=207

**Comment by durswd** [comment]
I will write how to export loop animation in detail later (Japan is in the midnight)

It is developing version and it may have bugs.

In global setting, it can specify a random seed. If it is larger than 0, random is fixed.
![image](https://user-images.githubusercontent.com/5775729/56096090-a4336500-5f1e-11e9-90dc-cad819b7eb87.png)

In behavior, it realizes that effects are spawn by specified time with random seed.
![image](https://user-images.githubusercontent.com/5775729/56096110-d3e26d00-5f1e-11e9-92ec-d70a892b7441.png)

In developing version, recording runs with the behavior parameters.

https://github.com/effekseer/Effekseer/releases/download/NightlyBuild/Effekseer20190415.zip

You create a short effect and specify random seed and Generating time.
Then you export animation  from 1 to 40
1-x starting animation
x-40 loop animation
are exported.

I'd like to fix bugs and enhance exporting animation in this week.

Best regards.

**Comment by zoltan-mihalyi** [comment]
Thank you! I managed to create a perfect loop animation.
But when I exported a sprite sheet, the program created one extra row. Is it a bug?

**Comment by durswd** [comment]
I think it is bug.
I will fix it in this weekend.

**Comment by durswd** [comment]
Fixed a bug.
https://github.com/effekseer/Effekseer/releases/download/NightlyBuild/EffekseerWin190420.zip

I will add new functions to improve 2D recording.
