### ISSUE TITLE
Incorrect decimal separator used when saving

### ISSUE THREAD

**Issue by zoltan-mihalyi** [effekseer/Effekseer#141]
On my computer, the default decimal separator is the comma, and it seems like it is used when saving the project. These values are lost when opening the project again 
```xml
<X>
    <Center>0,2</Center>
    <Max>0,2</Max>
    <Min>0,2</Min>
</X>
```

**Comment by durswd** [comment]
Thank you for your information.
It is easy to fix it.
Please wait tomorrow.

**Comment by durswd** [comment]
I fixed it.
Please try it and I'm grad if you tell me a result.

https://github.com/effekseer/Effekseer/releases/download/NightlyBuild/Effekseer20190410.zip

**Comment by zoltan-mihalyi** [comment]
Thank you, it works well!

**Comment by durswd** [comment]
Fixed other bugs.

https://github.com/effekseer/Effekseer/releases/download/NightlyBuild/Effekseer20190415.zip
