### ISSUE TITLE
Save record settings with project

### ISSUE THREAD

**Issue by zoltan-mihalyi** [effekseer/Effekseer#144]
The view and record settings are application specific. But the projects are exported with different settings.
If the record settings (resolution, frame rate, etc.) could be saved with the project, setting them manually before exporting would be avoidable.
Maybe this could be an option (save view and record settings with project or not). What do you think?

**Comment by durswd** [comment]
OK. I will implement it.

**Comment by durswd** [comment]
I'm working for Unity Plugin. This function is going to implemented after a few days

**Comment by zoltan-mihalyi** [comment]
Thank you!

**Comment by durswd** [comment]
https://github.com/effekseer/Effekseer/commit/9a2d039977e1e11c912e87df261958e4dba9750d
