### ISSUE TITLE
Point ot Attraction bugged when used magnification

### ISSUE THREAD

**Issue by igorsegallafa** [effekseer/Effekseer#146]
When used magnification to create effect (I have to), looks the point of attraction is bugged. Only nodes using point of attraction, dont know why this happens.

**No magnification (1.0f)**
![nomag](https://user-images.githubusercontent.com/36571229/57254034-a0c76100-7026-11e9-9496-605506a62420.gif)

**Using magnification (14.0f)**
![mag](https://user-images.githubusercontent.com/36571229/57254062-b3da3100-7026-11e9-84de-972df3b43194.gif)

_I used effect sample "Homing_Laser01" for test it_

**Comment by durswd** [comment]
I think It should be magnify a target position (14.0f) if you needs same behavior
