### ISSUE TITLE
UnityProでエフェクトを実行するとクラッシュする件について(自己解決済みですが報告までに)

### ISSUE THREAD

**Issue by KRNKRS** [effekseer/Effekseer#15]
UnityProにて、自作したエフェクトファイルを実行しようとするとクラッシュしました。
しかしこれは自己解決しまして、原因は、Effekseerの実行できるのがDX9のみと書いているにもかかわらず、Unityの設定をDX11にしていたためでした。

完全に自分のミスでした申し訳ありませんでした。
もう一つ気になった点があったのですがそれは別件でIssueします。

**Comment by ueshita** [comment]
今更になりますがDX11対応しました。
なお現時点の最新パッケージには含まれていないため、必要でしたらビルドして使用してください。
