### ISSUE TITLE
Check whether sample effects are stopped

### ISSUE THREAD

**Issue by durswd** [effekseer/Effekseer#157]
Check all sample effects are stopped and too long with Effekseer except loop effect
If something is wrong, fix it and reupload.

Effekseerを使用してループエフェクト以外のサンプルエフェクトが停止するか、長すぎないか確認する。
おかしいようなら、修正して再アップロードする。

https://effekseer.github.io/en/contribute.html

![image](https://user-images.githubusercontent.com/5775729/59692267-81c00f80-921f-11e9-8b5d-00b976661e83.png)

**Comment by sayuswd** [comment]
I think checked sample effects too long.
Effekseer01 File (Laser03.efkproj)
Pierre02_130 file (Benediction.efkproj , CosmicMist.efkproj , FeatherBomb.efkproj , FireBall.efkproj , LossOfBlood.efkproj , Sword_Lightning.efkproj )

**Comment by durswd** [comment]
https://github.com/effekseer/Website/tree/master/contributes/effects

**Comment by durswd** [comment]
AndrewFM01 - Fixed
Effekseer01 - Fixed
MAGICALxSPIRAL - Much problems
NextSoft01 - Fixed
NitoriBox - Want to change textures
Pierre01 - Fixed
Pierre02 - Fixed
ProjectDanmakuGirls - Unchecked
Suzuki01 - Unchecked
tktk01 - Unchecked
tktk02 - Unchecked
TouhouStrategy - Unchecked
