### ISSUE TITLE
UnityProでImageEffectのアンチエイリアスをかけると、エフェクトの挙動がおかしくなります

### ISSUE THREAD

**Issue by KRNKRS** [effekseer/Effekseer#16]
前Issueに引き続きの連投失礼致します。

UnityProでのエフェクトの再生には成功したのですが、UnityPro専用である「ImageEffect」のアンチエイリアスをかけた状態で実行すると、エフェクトが斜めを向き、カメラが動くと同時にエフェクトも動いてしまいます。スクリプト等で移動する処理を書いているわけでもなく、シーンビューで確認してもエフェクト自体はその場から動いてはいませんでした。ゲーム実行画面でのみ、上記挙動が発生します。

また、実行中だとエフェクトがかなりちらつきます。こちらはPCのスペックの問題なのでしょうか。

なにか解決策はございますでしょうか。
ご返信お待ちしております。

参考までに動画を用意しましたので、こちらを参照願います。
http://www.nicovideo.jp/watch/sm24449690

**Comment by ueshita** [comment]
これも今更ですが修正しました。
Unity4.6から挙動が変わっていたようです…。こちらで試していたのは4.5.3でした。
最新リリースパッケージにはまだ含まれていないので、必要でしたらビルドして使用してください。
