### ISSUE TITLE
x64でビルド(実行)できません

### ISSUE THREAD

**Issue by snakegtrr35** [effekseer/Effekseer#165]
EffekseerRuntime143b\RuntimeSample\DirectX11.sln をx64でビルド(実行)しようとしたところ、
リンカーエラーでビルドできませんでした。main.cpp内のpragma commentの部分をVS2015からVS2015WIN64に変えれば、ビルドは通るのですが、何も表示されません。恐らく、VS2015WIN64内のlibファイルが原因だと思うのですが、解決策が分かりません。

なにか解決策はありますでしょうか。
ご返信お待ちしております。

**Comment by durswd** [comment]
確認してみますので少々お待ちください。

**Comment by durswd** [comment]
単純にx64に変更した場合、出力先のファイルパスも変わるため、エフェクトのファイルの配置場所を変えるか出力先のファイルパスを変える必要がありますが、そこは大丈夫でしょうか？

**Comment by snakegtrr35** [comment]
エフェクトのファイルの配置場所を変えるときちんと表示されました。夜遅くなのに、本当にありがとうございます。
また、機会があれば質問させていただきます。ありがとうございました。

**Comment by durswd** [comment]
了解しました。
64bit環境も増えてきているのでもう少しわかりやすくしたいところです。
