### ISSUE TITLE
want coverter betwen .efk and .pu/.plist

### ISSUE THREAD

**Issue by xiangwencheng1994** [effekseer/Effekseer#168]
Can I covert .pu/.plist to .efk or other way ?

**Comment by durswd** [comment]
No and no plan.
What is the purpose or it?

**Comment by xiangwencheng1994** [comment]
I want to use effekseer on my project but some particle has design by PU，some engine already has a lot of particle file like .pu or .plist，it's wondful that we can covert to .efk

**Comment by durswd** [comment]
I read a document, I think it is difficult.
I recommend to use both tools.
