### ISSUE TITLE
press space to play start in code editor

### ISSUE THREAD

**Issue by mikkame** [effekseer/Effekseer#207]
.基本的に問題ないんですが
動的パラメーター画面外にマウスを外すとカーソルがエディターにフォーカスしていても
スペースで再生が開始してしまうっぽい気がします

**Comment by mikkame** [comment]
[effekseer#207.mov.zip](https://github.com/effekseer/Effekseer/files/3586758/effekseer.207.mov.zip)

**Comment by durswd** [comment]
Fixed
https://github.com/effekseer/Effekseer/commit/54fd2daf98af7e668cc0518b8ed08c605da493db
