### ISSUE TITLE
Add limitation of tree node max generation (最大ツリーノード世代数の制限を加える)

### ISSUE THREAD

**Issue by durswd** [effekseer/Effekseer#228]
a limitation of tree node generation is caused by optimizing.
It should shows an warning when generation is over than the number of maximum limitation in the tool.

最適化により、世代数の制限が生じてしまった。
最大世代数を超えたらツールで警告を出すようにする。

**Comment by ueshita** [comment]
対応 https://github.com/effekseer/Effekseer/commit/cf4f17221c6d51a39fc02a19349102c4b36bd7ba
※issue番号は間違い
