### ISSUE TITLE
Improve color of Fcurve to easy to see (見やすくなるようにFカーブの色を変える)

### ISSUE THREAD

**Issue by durswd** [effekseer/Effekseer#275]
Improve color of Fcurve to easy to see

見やすくなるようにFカーブの色を変える

Example (サンプル) Blender2.8

![image](https://user-images.githubusercontent.com/5775729/69901065-aff56e00-13bf-11ea-8319-f1275bdd6db6.png)

Current Effekseer (現在のEffekseer)
![image](https://user-images.githubusercontent.com/5775729/69901070-dc10ef00-13bf-11ea-8c1b-59046c024d6b.png)

too vivid
鮮やかすぎる

Code

https://github.com/effekseer/Effekseer/blob/master/Dev/Editor/Effekseer/GUI/Dock/FCurves.cs#L1320

https://github.com/effekseer/Effekseer/blob/master/Dev/Editor/Effekseer/GUI/Dock/FCurves.cs#L1339

https://github.com/effekseer/Effekseer/blob/master/Dev/Editor/Effekseer/GUI/Dock/FCurves.cs#L1356

In addition, It is better to refactor it
リファクタリングもすることが望ましい

**Comment by ueshita** [comment]
FカーブのUIを諸々調整しました。
- カーブの色
- ハンドルの形状
- 描画順

**Comment by durswd** [comment]
Thank you!
