### ISSUE TITLE
Better english translation of the description

### ISSUE THREAD

**Issue by Jummit** [effekseer/Effekseer#363]
I just translated the japanese description with [this website](https://translate.yandex.com/?lang=ja-en&text=%E6%9C%AC%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2%E3%81%AF%E3%83%91%E3%83%BC%E3%83%86%E3%82%A3%E3%82%AF%E3%83%AB%E3%82%A8%E3%83%95%E3%82%A7%E3%82%AF%E3%83%88%E7%B7%A8%E9%9B%86%E3%83%84%E3%83%BC%E3%83%AB%E3%81%A7%E3%81%99%E3%80%82%20%E3%83%A9%E3%83%B3%E3%82%BF%E3%82%A4%E3%83%A0%E3%82%84%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3%E3%82%92%E7%B5%84%E3%81%BF%E8%BE%BC%E3%82%80%E3%81%93%E3%81%A8%E3%81%A7%E3%80%81Effekseer%E3%81%A7%E4%BD%9C%E6%88%90%E3%81%95%E3%82%8C%E3%81%9F%E3%82%A8%E3%83%95%E3%82%A7%E3%82%AF%E3%83%88%E3%82%92%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E4%B8%AD%E3%81%A7%E5%86%8D%E7%94%9F%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82%20%E4%B8%BB%E3%81%AB%E3%82%B2%E3%83%BC%E3%83%A0%E3%81%A7%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%E3%81%93%E3%81%A8%E3%82%92%E6%83%B3%E5%AE%9A%E3%81%97%E3%81%A6%E3%81%8A%E3%82%8A%E3%80%81%E3%83%91%E3%83%BC%E3%83%86%E3%82%A3%E3%82%AF%E3%83%AB%E3%82%A8%E3%83%95%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E7%B7%A8%E9%9B%86%E3%82%92%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9E%E3%81%A7%E3%81%AA%E3%81%8F%E3%83%87%E3%82%B6%E3%82%A4%E3%83%8A%E3%83%BC%E3%81%8C%E6%8B%85%E5%BD%93%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%97%E3%81%BE%E3%81%99%E3%80%82), and the results are worded a little better than the current translation:

> This software is a particle effect editing tool. By incorporating runtime plug-ins, effects created by Effekseer can be played back in multiple applications. It is intended primarily for use in games, and allows designers, not just programmers, to edit particle effects.

Old:

> This software is a tool editing particle effects. By incorporating a runtime and plug-ins, you will be able to show the effects that was created with Effekseer. Effekseer is useful in developing game software especially. Not only programmers but also designers take charge of particle effects.

**Comment by durswd** [comment]
Thank you for your suggestion. I felt that the original description is not good and so I fixed it.
I translate it with DeepL (It is one of the machine translation for Japanese)

What do you feel about this?

New translation
```
This software is a particle effect editing tool. By incorporating runtimes and plug-ins, effects created in Effekseer can be played back in your application. Effekseer is intended to be used primarily for games, allowing the designer, not the programmer, to be in charge of editing particle effects.
```

- New
```
本ソフトウェアはパーティクルエフェクト編集ツールです。 ランタイムやプラグインを組み込むことで、Effekseerで作成されたエフェクトをアプリケーション中で再生できるようになります。 Effekseerは主にゲーム向けに使用することを想定しており、パーティクルエフェクトの編集をプログラマではなくデザイナーが担当できるようにします。
```

- Old
```
本ソフトウェアはパーティクルエフェクト編集ツールです。 ランタイムやプラグインを組み込むことで、Effekseerで作成されたエフェクトをアプリケーション中で再生できるようになります。 主にゲームで使用することを想定しており、パーティクルエフェクトの編集をプログラマでなくデザイナーが担当できるようにします。
```

**Comment by Jummit** [comment]
Looks good to me.

**Comment by durswd** [comment]
Thank you. I will replace it
