### ISSUE TITLE
Drawcalls are not batched in WebGL Version

### ISSUE THREAD

**Issue by yoki0805** [effekseer/Effekseer#384]
Hola!
It shows 4 drawcalls in editor, but actually it draws over 4 times in website.
It seems not batched in WebGL Version?
I'm using the v1.52b, and check the drawcalls by spector.js.
Gracias.

**Comment by durswd** [comment]
A model is not batched in WebGL version at least.
If sprites only exists, it is a bug of WebGL version.
What effect are you showing?

**Comment by yoki0805** [comment]
![2020-05-13_185400](https://user-images.githubusercontent.com/17826106/81804091-2ab7dd00-954b-11ea-8ce2-bc78d814d82b.png)
Something like this, a portal effect with sprites, particles, and strips.
I thought there's no model.

**Comment by durswd** [comment]
https://github.com/effekseer/EffekseerForWebGL/blob/master/src/js/effekseer.src.js#L537
Please specify a large value in this parameters.

If draw call is not decreased, it is a bug. I try to reproduce this bug.

**Comment by yoki0805** [comment]
I will try it. Thanks :)

**Comment by yoki0805** [comment]
Good day!
I increase the value of instanceMaxCount & squareMaxCount, and the number of drawcall is not changed.
We use the sprite, ribbon and track types. So is it a bug?
![642191](https://user-images.githubusercontent.com/17826106/81882965-9db26980-95c6-11ea-9f4b-5256e32ede61.jpg)

**Comment by durswd** [comment]
No. InstanceMaxCount and  squareMaxCount means the maximum number of polygons by a draw call.

**Comment by yoki0805** [comment]
Oh, I got it. The value is to make adjustment to the vertex buffer size.

**Comment by yoki0805** [comment]
Hi~I modify the demo of WebGL version, and put some effects in it.
Can you check this problem? Thanks. <3
[EffekseerForWebGL152f.zip](https://github.com/effekseer/Effekseer/files/4648638/EffekseerForWebGL152f.zip)

**Comment by durswd** [comment]
I saw this demo.
What is wrong?
It seems that good effects are shown.

**Comment by yoki0805** [comment]
It looks good, but the draw calls are not batched.
Ribbons or tracks are drawn many times,  especially. :(

**Comment by durswd** [comment]
OK. I will check... But I'm a bit busy in May. Checking is slow...

**Comment by yoki0805** [comment]
Great, thanks for your patience.

**Comment by durswd** [comment]
I finished my main work. I will tackle this issue.

**Comment by durswd** [comment]
@yoki0805 Excuse me. Please give me an efkproj file to check a behavior?

**Comment by yoki0805** [comment]
Sure! Here you are. :)
Please, open it with editor 152f version.
[DarkDoor_all.zip](https://github.com/effekseer/Effekseer/files/4744256/DarkDoor_all.zip)

**Comment by durswd** [comment]
I fixed a bug. Batching is now working.

https://github.com/effekseer/EffekseerForWebGL/releases/tag/152g

**Comment by yoki0805** [comment]
It works great!
The number of drawcalls is decrease now.
Thanks for your helping & hard work. :D
