### ISSUE TITLE
Package exporting

### ISSUE THREAD

**Issue by ueshita** [effekseer/Effekseer#415]
コミュニティ間で作成したエフェクトを共有するため、1ファイルにefkefcと依存するテクスチャ、モデル、サウンド等をまとめるパッケージシステム（unitypackageのようなもの）が欲しいです。

I want a package system (such as unitypackage) that collects textures, models, sounds, etc. that depend on efkefc in one file to share the created effects among the community.

# Specification
- Add menu to file->import/export
- Zip based format
  - .efkpackage or .efkpkg?
  - Includes metafile?

## Export
- Add export dialog.
- Find resource files that depend on efkefc and include them in the package

## Import
- Add import dialog.
- Choose the output destination of the resource file
- Check for existing duplicate resources

**Comment by durswd** [comment]
編集しやすくするために、解凍したままテクスチャの再配置、共通化等の機能もあるといい。

To make it easier to edit, it would be nice to have the ability to rearrange textures as they are decompressed, commonality, etc.

**Comment by durswd** [comment]
例えばパッケージを経由して簡単にテクスチャのディレクトリを置き換えたい

For example, I want to replace the texture directory easily via a package

Texture -> Textures

**Comment by durswd** [comment]
- アトラス化に対応してほしい
- CUIのみで動作してほしい

**Comment by ueshita** [comment]
> 編集しやすくするために、解凍したままテクスチャの再配置、共通化等の機能もあるといい。
> 例えばパッケージを経由して簡単にテクスチャのディレクトリを置き換えたい

それはそういうリソース依存関係を修正する機能(ダイアログ)を別に作ったほうがいいと思います。

> アトラス化に対応してほしい

上記と同じです。

> CUIのみで動作してほしい

これは出来そうですね。
