### ISSUE TITLE
EffekseerRuntime152hでlibとincが生成されない

### ISSUE THREAD

**Issue by siryuu0725** [effekseer/Effekseer#422]
Cmakeを含まないプロジェクトで使用しようと思っていたのですが、txtに書いてあった手順通りに行っても、libとincが生成されませんでした。
VC2019で使用するため、
手順は
①build_msvc2019.batを実行
②build_msvc2019ファイいるが生成
③中身無し

**Comment by durswd** [comment]
この情報だけだとわからないので、build_msvc2019.batを実行したときのログを送っていただけないでしょうか？

**Comment by siryuu0725** [comment]
申し訳ございません。
以下実行結果のログです
--------------------------------------------------------------------------------------------------------------------------------------

c:\EffekseerRuntime152h>build_msvc2019.bat

c:\EffekseerRuntime152h>mkdir build_msvc2019

c:\EffekseerRuntime152h>cd build_msvc2019

c:\EffekseerRuntime152h\build_msvc2019>cmake -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=../install_msvc2019 -DUSE_LLGI=ON -DBUILD_DX12=ON .. -DCMAKE_DEBUG_POSTFIX=d
'cmake' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。

c:\EffekseerRuntime152h\build_msvc2019>cmake --build . --config Debug --target INSTALL
'cmake' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。

c:\EffekseerRuntime152h\build_msvc2019>cmake --build . --config Release --target INSTALL
'cmake' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。

**Comment by durswd** [comment]
'cmake' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。

と書いてある通り、cmakeにパスが通ってない可能性が高いです。
まずはcmdからcmakeを実行してみてはいかがでしょうか？

**Comment by siryuu0725** [comment]
生成することができました。
ありがとうございます！
