### ISSUE TITLE
Compile in linux?

### ISSUE THREAD

**Issue by Dev-Matias** [effekseer/Effekseer#431]
How to compile in linux?

**Comment by durswd** [comment]
Please read it
https://github.com/effekseer/Effekseer/blob/master/docs/Development/HowToBuild.md

or use docker image
https://github.com/effekseer/Effekseer/tree/master/Docker/Ubuntu

**Comment by Dev-Matias** [comment]
Error to compile, any solution for this error
FAILED: Examples/Utils/CMakeFiles/Example_Utils.dir/Linux/Window.cpp.o
fatal error: X11/Xlib-xcb.h: No existe el archivo o el directorio

**Comment by durswd** [comment]
apt-get install libx11-xcb-dev

**Comment by Dev-Matias** [comment]
**Thanks** it works, but with some errors
![Screenshot from 2020-07-22 11-48-03](https://user-images.githubusercontent.com/23369681/88191321-b1ef9400-cc11-11ea-9647-97da07e196d5.png)
**It works**
![Screenshot from 2020-07-22 11-48-15](https://user-images.githubusercontent.com/23369681/88191633-08f56900-cc12-11ea-99da-fa27a466d3c2.png)

**Comment by durswd** [comment]
Effekseer for linux is under developing. If you interested in it, it is welcome to PR.

**Comment by durswd** [comment]
I fixed about error messages.
