### ISSUE TITLE
Problem with F-Curve option for UV on Basic Render Settings

### ISSUE THREAD

**Issue by LionBlade** [effekseer/Effekseer#435]
When I tried to use the F-Curve option for UV on the Basic Render Settings as I wanted to have more control over animating a sprite sheet, I noticed that the Size and the Start for the F-Curve option doesn't work in the same way as the Size and Start for the Animation option and the Fixed option.  I was trying to set the Size of a sprite sheet frame (which is 192x192) through the F-Curve, but the exact image frame kept on not being accurately within the frame size whenever I inputted the frame size through the F-Curve Size.
![UV_F_Curve_BasicRenderSetting](https://user-images.githubusercontent.com/22432346/88467253-25f49b00-cea3-11ea-924e-160a4e3f6f3e.png)
Furthermore, there's a problem with making the F-Curve Start accurate due to having a problem that may be associated with F-Curve Size.  On the other hand, the Animation option and the Fixed option don't have the problem that F-Curve has and I can get the exact image frame on Size (particularly, when Referenced is set to Image1).
![UV_Animation_BasicRenderSetting](https://user-images.githubusercontent.com/22432346/88467260-37d63e00-cea3-11ea-8643-3888233497af.png)
Is there a way for you to make the Size and the Start from the UV F-Curve option be accurate, like the Size and the Start from the UV Animation option and from the UV Fixed option, please?

**Comment by durswd** [comment]
Thank you for your report.
I will fix it.

**Comment by LionBlade** [comment]
You are welcome!

**Comment by durswd** [comment]
It was fixed on the repository.
I will release new version a few days later.

**Comment by LionBlade** [comment]
Awesome!  Thanks for letting me know!

**Comment by LionBlade** [comment]
@durswd - The fix for UV's F-Curve option is working really great, allowing the F-Curve option to be a good alternative to the Animation option.  I want to thank you for the update.
