### ISSUE TITLE
Link failed some shaders with WebGL on iOS.

### ISSUE THREAD

**Issue by hiroshi-nishiura** [effekseer/Effekseer#486]
現在開発中のWebアプリでEffekseerForWebGLを実装しています。
Desktop/Androidでは動作しましたが、iOSだと基本シェーダのリンクで失敗するものがありました。
iPad 第２世代と第５世代で確認。

Effekseer/Dev/Cpp/EffekseerRendererGL/EffekseerRenderer/EffekseerRendererGL.Shader.cpp の
GLExt::glGetProgramInfoLog(program, sizeof(log), &log_size, log) でエラー内容が得られるはずですが
何故か取得できないため、具体的な要因を提示できないのですが、内部を追跡したところ、

* model_renderer_distortion
* standard_renderer_lighting

の２つのシェーダでリンクエラーになっていました。原因は、varyingパラメータ数がMax値を超えているためでした。
iOSのGLES2のMaxVaryingVectorsは最小値である８なので、渡せるパラメータ数はトータル8x4までしか使えません。

運がいいことに、Fragment側で使用していないvaryingを削除することでリンクが通り、描画も問題なくなりました。
具体的には、
model_renderer_distortionは、varying  vec4 _VSPS_Normal
standard_renderer_lightingは、varying  vec3 _VSPS_WorldP
を削除することで解決しました。

**Comment by durswd** [comment]
報告ありがとうございます。
ちなみに、これが発生したのはmasterブランチでしょうか？

**Comment by hiroshi-nishiura** [comment]
はい。1weekくらい前にクローンしたmasterです。

**Comment by durswd** [comment]
了解しました。masterは現在、シェーダーを大きく変更中で、それによって生じた不具合です。
随時対応していきます。

**Comment by hiroshi-nishiura** [comment]
よろしくお願いします。

**Comment by durswd** [comment]
取り急ぎ、上記指摘部分を削りました。

**Comment by hiroshi-nishiura** [comment]
すみません、確認遅くなりました。masterブランチで問題ないことを確認できました。
ありがとうございました。
