### ISSUE TITLE
The effect is getting the wrong display while showing the duplicate effect

### ISSUE THREAD

**Issue by doandoindi** [effekseer/Effekseer#497]
I'm trying to create the Fire Effekseer effect. Unfortunately, I got the problem while showing it.

I'm attaching the effect + demo source (based on the OpenGL example)
[Resources.zip](https://github.com/effekseer/Effekseer/files/5213748/Resources.zip)

Both effects have the right display if *nb_effect* set to 5 while **Fire6.efk** will get the wrong display if *nb_effect* set to 10.
Could you take a look at this issue?

**Comment by durswd** [comment]
auto renderer = ::EffekseerRendererGL::Renderer::Create(8000, EffekseerRendererGL::OpenGLDeviceType::OpenGL3);

please change 8000 into more large value.

**Comment by doandoindi** [comment]
You save me a lot of time. Thank you!
