### ISSUE TITLE
Unityアセットバンドルのビルドスクリプトがコンパイルエラーになってました

### ISSUE THREAD

**Issue by kou-yeung** [effekseer/Effekseer#50]
Unity5.4.0f3 で確認しました。

5.0 以降 BuildPipeline.BuildAssetBundleExplicitAssetNames が廃止されたため
代わりに BuildPipeline.BuildAssetBundles を使用したバージョンを書きました。

Github上 EffekseerAssetBundleBuilder.cs がなかったようですので
Gist のリンクを貼ります。
https://gist.github.com/kou-yeung/c47ebc826a79f2e9279cb0889954ba00

**Comment by ueshita** [comment]
ありがとうございます。
現在Unityプラグインは別リポジトリに移行しようとしているので、そちらでマージさせていただきます。

**Comment by kou-yeung** [comment]
わかりました。
よろしくお願いします。

**Comment by effekseer** [comment]
Unityリポジトリはこちらです。
https://github.com/effekseer/EffekseerForUnity
