### ISSUE TITLE
Can't input decimal separator in linux.

### ISSUE THREAD

**Issue by riccardobl** [effekseer/Effekseer#505]
When inputing decimal numbers in the UI, the comma  is not registered (pressing it does not insert the character) and the dot doesn't seem to be a valid decimal separator.
The build is a snapshot from the master branch
OS: **ubuntu 18.04**
system language: **english**
input language **Italian (US, with italian letters)**

**Comment by durswd** [comment]
It seem that It causes by a difference between EU and US.
I will check it but I need to take a much time because I prepare Italian environment.
I'm glad if you fix it because an environment bug is difficult.

**Comment by riccardobl** [comment]
I'll try to look into that. But i never used imgui, so i might not be able to pinpoint the issue.
Do you have any theories on how it could be fixed?

**Comment by riccardobl** [comment]
Ok, this issue seems related to https://github.com/ocornut/imgui/issues/2278 .
The newer imgui has a way to set the decimal point
` ImGui::GetCurrentContext()->PlatformLocaleDecimalPoint = *localeconv()->decimal_point; `
However from the commit history of the effekseer repo i noticed that imgui was updated but then the commit was reverted.
Is there anything that is preventing the editor from working with a newer version of imgui?

**Comment by riccardobl** [comment]
So, it seems that the version used in effekseer is an old snapshot of the docking branch. 
For now, until it can be upgraded, i applied the commit that fixes this specific issue into the current version.
Pr https://github.com/effekseer/Effekseer/pull/506
