### ISSUE TITLE
mqoToEffekseerModelConverter.exe

### ISSUE THREAD

**Issue by Wizterian** [effekseer/Effekseer#532]
Always thankful to your great product "Effekseer" and support.
Is "mqoToEffekseerModelConverter.exe" still available on your web site now?
I'm trying to put a logo effect in the website I'm working on next month. It moves along the edge of the 3D model logo. So I think it requires ".mqo file" AND "mqoToEffekseerModelConverter.exe". I'm afraid I can't find out the "."EXE" file. I'm wondering if it's still available or not.

**Comment by durswd** [comment]
mqoToEffekseerModelConverter.exe is contained in Tool/tools/ 
And it calls automatically from Effekseer when models are loaded

**Comment by Wizterian** [comment]
Thank you very much for your reply.
I got that it works automatically when 3D models loaded. (^^)
