### ISSUE TITLE
Failed to reset device lost on DirectX9

### ISSUE THREAD

**Issue by effekseer** [effekseer/Effekseer#56]

**Comment by oigami** [comment]
[ここ](https://github.com/effekseer/Effekseer/blob/master/Dev/Cpp/EffekseerRendererDX9/EffekseerRenderer/EffekseerRendererDX9.TextureLoader.cpp#L50)で確保されたテクスチャの処理がないようです。
![a](https://cloud.githubusercontent.com/assets/10395699/20359740/7b362192-ac74-11e6-904e-f1bb8e45d566.PNG)

どこに処理を追加するか難しいので修正はおまかせします。よろしくお願いします。

**Comment by effekseer** [comment]
このような方法で対応しました。
https://github.com/effekseer/Effekseer/commit/380c7dfb7be34bc07e89c2142b2a789729557450
