### ISSUE TITLE
Performance issue, the glGet calls are slow

### ISSUE THREAD

**Issue by yoki0805** [effekseer/Effekseer#582]
Version: EffekseerForWebGL 152h
Description: the glGet calls make context.draw() slow
--
Effekseer uses a lot of glGet calls, and it makes the render time increase.
I used the developer tool to check the call tree, the glGet calls make performance pretty slow.
OpenGL suggests that developers advoid them. [(more information)](https://www.khronos.org/opengl/wiki/Common_Mistakes#glGetFloatv_glGetBooleanv_glGetDoublev_glGetIntegerv)

![2020-11-30_194609](https://user-images.githubusercontent.com/17826106/100606825-f66c0880-3344-11eb-9211-9151bbc44c57.png)

**Comment by durswd** [comment]
OK. I will check it

**Comment by durswd** [comment]
I added a flag to make glGet disabled

https://github.com/effekseer/EffekseerForWebGL/commit/69bbccaad024ee391fdb3909c3dcef4c09f12753
