### ISSUE TITLE
消滅処理について

### ISSUE THREAD

**Issue by siromiya** [effekseer/Effekseer#62]
初めまして。
先日ゲームを作るためにEffekseerをダウンロードさせていただきました。

プレイヤーの周りを光の渦が回るように演出をしたいのですが、設定した時間が来ると一度すべて消えてしまいます。できればずっと渦を巻いていてほしいのですが、特定時間の繰り返しや、消滅しないようにすることはできましでしょうか?

**Comment by effekseer** [comment]
共通パネルの「寿命により削除」のチェックを外すことにより、特定の時間が来ても消滅しないようになります。
