### ISSUE TITLE
Effekseer can't start!!

### ISSUE THREAD

**Issue by mis0025033** [effekseer/Effekseer#63]
Hi,
I am going to try this amazing software, but it prompt a warning dialog box when i execute the software.
The warning is about the issue of the version of DirectX or the memory is not enough. 
How can i solve the problem???
I am using windows10 , Direct X 12, 16Gb ram

Thanks

**Comment by effekseer** [comment]
Thank you for your interesting.
I think that you need to install DirectX EndUserRuntime.
This software uses directX9.

https://www.microsoft.com/en-US/download/details.aspx?id=35

**Comment by durswd** [comment]
I updated readme.
Required runtimes are added.

https://github.com/effekseer/Effekseer/blob/master/readme_tool.txt

**Comment by mis0025033** [comment]
Thx for your help, I can use effekseer now.
And i have one more question, can I change the interface to Eng ???

Thank you

2017-02-07 8:02 GMT+08:00 swd <notifications@github.com>:

**Comment by effekseer** [comment]
Nightly build version does not supports English interface currently.
1.22 supports English interface.
Basically, languages are selected automatically.
Language is also selected manually in menu bar -> オプション -> 言語設定 -> 英語.

When the language of OS is english and the interface is Japanese, it is bug.
