### ISSUE TITLE
Linux next ?

### ISSUE THREAD

**Issue by TheFourchette** [effekseer/Effekseer#640]
It should be available for linux right ?

Please make it work on linux

**Comment by durswd** [comment]
You can use on linux if you compile Effekseer

**Comment by UnknownS1024** [comment]
@durswd I get an error when compile :( , need to officially download for linux without compile of all distributions :D

**Comment by follower** [comment]
FWIW as someone using software, I appreciate the ease-of-use from applications distributed in AppImage format: https://appimage.org

(I just tried to unsuccessfully run Effekseer via Wine. :) )
