### ISSUE TITLE
How to embed resources inside efkefc files?

### ISSUE THREAD

**Issue by ChronicallySerious** [effekseer/Effekseer#645]
I have a setup where I have the effekseer editor tool running in a separate directory than the one where I run the effekseer runtime in our engine from.

When I save the efkefc file from the tool, it can save to the engine directory. However in systems which do not have the image files used in the effect, they are not loaded properly and the display looks weird (image loading must have failed I assume)

**Comment by durswd** [comment]
I'm sorry. There is no method.
But you can change a root directory with materialPath.

```
static EffectRef Create(const ManagerRef& manager, const void* data, int32_t size, float magnification = 1.0f, const char16_t* materialPath = nullptr);
```

Otherwise you can extend a loader like this code

https://github.com/effekseer/Effekseer/blob/master/Examples/CustomBinary/main.cpp

**Comment by durswd** [comment]
3.

Effekseer 1.6 has a feature to packaging effect including dependencies.
But it is for the tool. You need to implement a loader for this package currently

**Comment by ChronicallySerious** [comment]
Thanks!
