### ISSUE TITLE
Effect reload function is always returning false

### ISSUE THREAD

**Issue by ChronicallySerious** [effekseer/Effekseer#647]
https://github.com/effekseer/Effekseer/blob/master/Dev/Cpp/Effekseer/Effekseer/Effekseer.Effect.cpp#L1322

This function seems to always return false. Is this intended?

**Comment by durswd** [comment]
No. Thank you

**Comment by durswd** [comment]
I fixed it

**Comment by ChronicallySerious** [comment]
Thanks a lot for the quick response! I will close this issue

**Comment by ChronicallySerious** [comment]
Actually there is another function just above that which does the same thing but it is a different overload

https://github.com/effekseer/Effekseer/blob/master/Dev/Cpp/Effekseer/Effekseer/Effekseer.Effect.cpp#L1264

I think this function also never returns true

**Comment by durswd** [comment]
I fixed it. Thank you

**Comment by ChronicallySerious** [comment]
Awesome!
