### ISSUE TITLE
Can import model 3d to effekseer at present ?

### ISSUE THREAD

**Issue by natsupy** [effekseer/Effekseer#65]
Hi your,
This is awesome software for make effect in unity, and i saw files sample, it have model 3d, so how can i import other model to this, have way to convert model to efkmodel ?
Thank you so much !

**Comment by effekseer** [comment]
Effekseer can import a metasequoia's file(.mqo) using mqoToEffekseerModelConverter.exe. This is a popular software in Japan.  I want to realize that FBX can be imported in the next version.

**Comment by natsupy** [comment]
i'll wait for you :D

**Comment by effekseer** [comment]
Currently working.

https://github.com/effekseer/Effekseer/commit/c32460d5ba32ebdf08a9b397d2e5c0df39de9664

**Comment by natsupy** [comment]
thank you so much, i'll try !

**Comment by effekseer** [comment]
Sorry for mistaking my English.
This version is incomplete.
I'll finish at weekend.

**Comment by effekseer** [comment]
Sorry. Unfortunately I'm sick now.

**Comment by natsupy** [comment]
no, dont worry, i can use blender for that, take care of yourself, get well soon ! Read Shonen Jump on your bed, if i were you :D

**Comment by effekseer** [comment]
We developed fbx converter.
Would you try it?

https://github.com/effekseer/Effekseer/releases/download/NightlyBuild/fbxToEffekseerModelConverter.zip

How to use.

fbxToEffekseerModelConverter xxx.fbx -o xxx.efkmdl (with any options.)

**Comment by natsupy** [comment]
thank you, but it seem not work on my computer, maybe i'm mistake something :(( you can public for people testing them

**Comment by effekseer** [comment]
mmm...
I think that your FBX file is wrong for this tool.
Please would you send me the fbx file?

**Comment by natsupy** [comment]
uhm...
http://www12.zippyshare.com/v/e8riZzw0/file.html
you can test this !

**Comment by effekseer** [comment]
uhm... I can convert this file using a command as follows.
fbxToEffekseerModelConverter.exe Sword.fbx

Converted file can be loaded only Effekseer Nigtly Build Version.
https://github.com/effekseer/Effekseer/releases/download/NightlyBuild/Effekseer170415.zip

**Comment by natsupy** [comment]
thank you so much, i can export model, but when export file to unity and run it, unity was crash ( nightly version),
old version is ok
btw i have the noise when using file example, like this, it happen with effect aura, what am i mistake, can you help to fix it ?
https://www.youtube.com/watch?v=TBgNz5eDFgQ&feature=youtu.be

**Comment by effekseer** [comment]
1.  3D model
3D model's format is updated. So EffekseerForUnity is required to update. I compiled new EffekseerForUnity(WinOnly, It is not debuged)
https://github.com/effekseer/Effekseer/releases/download/NightlyBuild/EffekseerForUnity170417WinOnly.zip

2. Example
The noise is caused. But the reason is not Effekseer or your bug. The structure of effect causes the noise.
To solve it, you remove a check from depth set in each nodes.

**Comment by natsupy** [comment]
thank you so much, it work pretty, i uncheck depth test each node, not have noise anymore

**Comment by effekseer** [comment]
We embedded the fbx loader into Effekseer 1.30.

**Comment by natsupy** [comment]
thank you so much! I'll check it!
