### ISSUE TITLE
[Linux] Unable to import models from blender

### ISSUE THREAD

**Issue by CassieLoYan** [effekseer/Effekseer#654]
Distribution: Arch Linux

Attempting to import a .fbx model made in Blender results in a "Error: Failed to load" message. Attempting to import a .mqo model results in no error message, however the model does not appear inside the editor. Importing the .mqo models from the documentation's tutorials, however, does work

Version: 1.60 Beta3

[ErrorExample.zip](https://github.com/effekseer/Effekseer/files/6255269/ErrorExample.zip)

Running Effekseer through the command line results in this error when importing the FBX model:
`$HOME/effekseer/Effekseer/Dev/release/tools/fbxToEffekseerModelConverter: error while loading shared libraries: libfbxsdk.so: cannot open shared object file: No such file or directory`

**Comment by durswd** [comment]
I will check it

**Comment by durswd** [comment]
I reproduced it. I will try to debug it.

**Comment by durswd** [comment]
It maybe fixed. 
I will check a behavior on Linux

https://github.com/effekseer/Effekseer/commit/47931142f05753fe22aa09486517e5e65224b66e

**Comment by durswd** [comment]
I fixed.
If you download from Github Actions, you need to chmod +x Effekseer and fbxToEffekseerModelConveter because of this problem
 https://github.com/actions/upload-artifact/issues/38
