### ISSUE TITLE
`__EFFEKSEER_NETWORK_DISABLED__` should be exposed as CMake option

### ISSUE THREAD

**Issue by JayFoxRox** [effekseer/Effekseer#667]
The code checks for `__EFFEKSEER_NETWORK_DISABLED__` which can be used to disable networking.
This option should be exposed from CMake, so it becomes easier to port Effekseer. As a workaround, I currently use:

```
cmake [...] -DCMAKE_CXX_FLAGS=-D__EFFEKSEER_NETWORK_DISABLED__=1 ..
```

**Comment by durswd** [comment]
I added NETWORK_ENABLED
