### ISSUE TITLE
Allow platform independent compilation of individual renderers

### ISSUE THREAD

**Issue by JayFoxRox** [effekseer/Effekseer#668]
- I found no way to disable GL rendering entirely. On my target platform, there's no OpenGL, so inclusion of `GL/gl.h` will fail.
There should be a CMake option to disable OpenGL entirely.

- My plan is to keep the renderer out-of-tree / implement it on a per-project basis or a separate library.
This effort might also benefit from EffekseerRendererCommon, which is currently only built for the Unity plugin.
I think this should be changed so it can be enabled explicitly, even when not compiling for Unity.

- Additionally, I'm compiling for an embedded version of Windows, which not only doesn't have OpenGL, but it also doesn't have DX9 or DX11.
There's currently no way to explicitly disable DX9 or DX11 for Windows.
Likewise, Linux and other operating systems are getting partial D3D support these days: https://devblogs.microsoft.com/directx/directx-heart-linux/ (and similar); so it makes sense to toggle these renderers individually (using the detected platform only as a cmake `option` hint).

**Comment by durswd** [comment]
I added options
