### ISSUE TITLE
Segmentation fault when running Effekseer on Linux with mesa ("0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES")

### ISSUE THREAD

**Issue by JayFoxRox** [effekseer/Effekseer#671]
My platform is Linux (x64), X11, mesa 21.0.3 graphics driver
When I ran a naively made built of Effekseer, it simply crashed at startup with "Segmentation fault (core dumped)" without any error message.

I built a debug build to investigate and I didn't even have to attach a debugger to know what's wrong:

```
$ ./Effekseer
UnlitAd: Vertex Shader error.
DeviceType=1
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES
UnlitAd: Fragment Shader error.
DeviceType=1
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES
UnlitAd: Shader Link error.
error: vertex shader lacks `main'
Segmentation fault (core dumped)
```

I suspect that I get an OpenGL 1 or 2 context, and not OpenGL 3. So the shader compilation fails.
This probably wasn't an issue on some other drivers, because they luckily picked another OpenGL version by default.

I looked into the code and tracked it down to this check for `__APPLE__`, which should not be necessary:

https://github.com/effekseer/Effekseer/blob/99aa65df3789acb5515e372773f0e084365f071d/Dev/Cpp/EditorCommon/GUI/MainWindow.cpp#L32-L42

The platform check around this code should be removed; all platforms (including Windows and Linux) should set these GL version hints in GLFW.

I also checked the shader selection for "UnlitAd" to ensure that it wasn't using GL 3.3 shaders for `DeviceType` GL2, and everything seems to be correct when skimming over it.
I also briefly checked if the `MainWindow` code should check the `DeviceType` to pick a matching OpenGL version, but noticed that ImGui is also initialized in GL3 mode, so it makes sense to force GL3 for the editor `MainWindow.`

**Comment by durswd** [comment]
I will check it on linux in a few days

**Comment by durswd** [comment]
https://github.com/effekseer/Effekseer/commit/f9e6a15ccb6996036592c6e9713a19b122dfbf7b
