### ISSUE TITLE
OpenGL function `GetIntetnalGraphicsDevice` has typo and should be called `GetInternalGraphicsDevice`

### ISSUE THREAD

**Issue by JayFoxRox** [effekseer/Effekseer#672]
Declared here (and used in many places):

https://github.com/effekseer/Effekseer/blob/7b62fd19e432d51730f5b89862cb8f301222f083/Dev/Cpp/EffekseerRendererGL/EffekseerRenderer/EffekseerRendererGL.RendererImplemented.h#L239

**Comment by durswd** [comment]
I fixed it. Thank you
