### ISSUE TITLE
compile on ubuntu 16.04 with gcc8 error

### ISSUE THREAD

**Issue by yangjianying** [effekseer/Effekseer#695]
[7/24] Building CXX object Dev/Cpp/Test/CMakeFiles/Test.dir/Runtime/EffectPlatform.cpp.o
../Dev/Cpp/Test/Runtime/EffectPlatform.cpp: In member function ‘Effekseer::Handle EffectPlatform::Play(const char16_t*, Effekseer::Vector3D, int32_t)’:
../Dev/Cpp/Test/Runtime/EffectPlatform.cpp:159:7: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
  fread(data.data(), 1, size, filePtr);
  ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[8/24] Building CXX object Dev/Cpp/Test/CMakeFiles/Test.dir/Runtime/Vertex.cpp.o
[9/24] Building CXX object Dev/Cpp/Test/CMakeFiles/Test.dir/Runtime/TextureFormats.cpp.o
[10/24] Building CXX object Dev/Cpp/Viewer/CMakeFiles/Viewer.dir/Graphics/Platform/GL/efk.PostEffectsGL.cpp.o
FAILED: Dev/Cpp/Viewer/CMakeFiles/Viewer.dir/Graphics/Platform/GL/efk.PostEffectsGL.cpp.o 
/usr/bin/c++ -DViewer_EXPORTS -D__EFFEKSEER_RENDERER_INTERNAL_LOADER__ -D__EFFEKSEER_USE_LIBPNG__ -D__EFFEKSEER_VIEWER_BUILD_AS_CMAKE__ -I../Dev/Cpp/Effekseer -I../Dev/Cpp/include -IThirdParty/Install/zlib/include -IThirdParty/Install/libpng/include -IThirdParty/Install/libgd/include -I../Downloads/OpenSoundMixer/src -IThirdParty/Install/glfw/include -I../Dev/Cpp/3rdParty/spdlog/include -I../Dev/Cpp/Viewer/../include -I../Dev/Cpp/Viewer/../EffekseerRendererDX9 -I../Dev/Cpp/Viewer/../EffekseerRendererGL -I../Dev/Cpp/Viewer/../EffekseerSoundOSMixer -I../Dev/Cpp/Viewer/.. -I../Dev/Cpp/EditorCommon -I../Dev/Cpp/3rdParty/Boxer -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I../Dev/Cpp/3rdParty/imgui -I../Dev/Cpp/3rdParty/nativefiledialog/src/include -O3 -DNDEBUG -fPIC -std=gnu++17 -MD -MT Dev/Cpp/Viewer/CMakeFiles/Viewer.dir/Graphics/Platform/GL/efk.PostEffectsGL.cpp.o -MF Dev/Cpp/Viewer/CMakeFiles/Viewer.dir/Graphics/Platform/GL/efk.PostEffectsGL.cpp.o.d -o Dev/Cpp/Viewer/CMakeFiles/Viewer.dir/Graphics/Platform/GL/efk.PostEffectsGL.cpp.o -c ../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp
In file included from ../Dev/Cpp/Viewer/../EffekseerRendererGL/EffekseerRenderer/GraphicsDevice.h:5,
                 from ../Dev/Cpp/Viewer/../EffekseerRendererGL/EffekseerRenderer/EffekseerRendererGL.DeviceObject.h:5,
                 from ../Dev/Cpp/Viewer/../EffekseerRendererGL/EffekseerRenderer/EffekseerRendererGL.IndexBuffer.h:8,
                 from ../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.h:5,
                 from ../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:8:
../Dev/Cpp/Viewer/../EffekseerRendererGL/EffekseerRenderer/EffekseerRendererGL.GLExtension.h:171: warning: "GL_WRITE_ONLY" redefined
 #define GL_WRITE_ONLY 0x000088b9
 
In file included from /usr/include/GL/gl.h:2055,
                 from ../Dev/Cpp/Viewer/../EffekseerRendererGL/EffekseerRenderer/EffekseerRendererGL.GLExtension.h:56,
                 from ../Dev/Cpp/Viewer/../EffekseerRendererGL/EffekseerRenderer/GraphicsDevice.h:5,
                 from ../Dev/Cpp/Viewer/../EffekseerRendererGL/EffekseerRenderer/EffekseerRendererGL.DeviceObject.h:5,
                 from ../Dev/Cpp/Viewer/../EffekseerRendererGL/EffekseerRenderer/EffekseerRendererGL.IndexBuffer.h:8,
                 from ../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.h:5,
                 from ../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:8:
/usr/include/GL/glext.h:482: note: this is the location of the previous definition
 #define GL_WRITE_ONLY                     0x88B9
 
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp: In member function ‘virtual void efk::BloomEffectGL::Render(Effekseer::Backend::TextureRef, Effekseer::Backend::TextureRef)’:
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:360:108: error: no matching function for call to ‘efk::BlitterGL::Blit(std::unique_ptr<EffekseerRendererGL::Shader>::pointer, std::unique_ptr<EffekseerRendererGL::VertexArray>::pointer, const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >&, std::nullptr_t, int, Effekseer::Backend::TextureRef)’
   blitter.Blit(shaderBlurH.get(), vaoBlurH.get(), textures, nullptr, 0, lowresBuffers[1][i]->GetAsBackend());
                                                                                                            ^
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note: candidate: ‘void efk::BlitterGL::Blit(EffekseerRendererGL::Shader*, EffekseerRendererGL::VertexArray*, const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&, const void*, size_t, Effekseer::Backend::TextureRef, bool)’
 void BlitterGL::Blit(EffekseerRendererGL::Shader* shader,
      ^~~~~~~~~
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note:   no known conversion for argument 3 from ‘const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >’ to ‘const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&’
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:367:108: error: no matching function for call to ‘efk::BlitterGL::Blit(std::unique_ptr<EffekseerRendererGL::Shader>::pointer, std::unique_ptr<EffekseerRendererGL::VertexArray>::pointer, const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >&, std::nullptr_t, int, Effekseer::Backend::TextureRef)’
   blitter.Blit(shaderBlurV.get(), vaoBlurV.get(), textures, nullptr, 0, lowresBuffers[0][i]->GetAsBackend());
                                                                                                            ^
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note: candidate: ‘void efk::BlitterGL::Blit(EffekseerRendererGL::Shader*, EffekseerRendererGL::VertexArray*, const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&, const void*, size_t, Effekseer::Backend::TextureRef, bool)’
 void BlitterGL::Blit(EffekseerRendererGL::Shader* shader,
      ^~~~~~~~~
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note:   no known conversion for argument 3 from ‘const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >’ to ‘const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&’
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:378:84: error: no matching function for call to ‘efk::BlitterGL::Blit(std::unique_ptr<EffekseerRendererGL::Shader>::pointer, std::unique_ptr<EffekseerRendererGL::VertexArray>::pointer, const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >&, std::nullptr_t, int, Effekseer::Backend::TextureRef&, bool)’
   blitter.Blit(shaderBlend.get(), vaoBlend.get(), textures, nullptr, 0, dest, false);
                                                                                    ^
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note: candidate: ‘void efk::BlitterGL::Blit(EffekseerRendererGL::Shader*, EffekseerRendererGL::VertexArray*, const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&, const void*, size_t, Effekseer::Backend::TextureRef, bool)’
 void BlitterGL::Blit(EffekseerRendererGL::Shader* shader,
      ^~~~~~~~~
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note:   no known conversion for argument 3 from ‘const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >’ to ‘const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&’
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp: In member function ‘virtual void efk::TonemapEffectGL::Render(Effekseer::Backend::TextureRef, Effekseer::Backend::TextureRef)’:
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:495:75: error: no matching function for call to ‘efk::BlitterGL::Blit(std::unique_ptr<EffekseerRendererGL::Shader>::pointer, std::unique_ptr<EffekseerRendererGL::VertexArray>::pointer, const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >&, std::nullptr_t, int, Effekseer::Backend::TextureRef&)’
   blitter.Blit(shaderCopy.get(), vaoCopy.get(), textures, nullptr, 0, dest);
                                                                           ^
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note: candidate: ‘void efk::BlitterGL::Blit(EffekseerRendererGL::Shader*, EffekseerRendererGL::VertexArray*, const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&, const void*, size_t, Effekseer::Backend::TextureRef, bool)’
 void BlitterGL::Blit(EffekseerRendererGL::Shader* shader,
      ^~~~~~~~~
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note:   no known conversion for argument 3 from ‘const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >’ to ‘const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&’
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:500:107: error: no matching function for call to ‘efk::BlitterGL::Blit(std::unique_ptr<EffekseerRendererGL::Shader>::pointer, std::unique_ptr<EffekseerRendererGL::VertexArray>::pointer, const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >&, const float [4], long unsigned int, Effekseer::Backend::TextureRef&)’
   blitter.Blit(shaderReinhard.get(), vaoReinhard.get(), textures, constantData, sizeof(constantData), dest);
                                                                                                           ^
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note: candidate: ‘void efk::BlitterGL::Blit(EffekseerRendererGL::Shader*, EffekseerRendererGL::VertexArray*, const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&, const void*, size_t, Effekseer::Backend::TextureRef, bool)’
 void BlitterGL::Blit(EffekseerRendererGL::Shader* shader,
      ^~~~~~~~~
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note:   no known conversion for argument 3 from ‘const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >’ to ‘const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&’
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp: In member function ‘virtual void efk::LinearToSRGBEffectGL::Render(Effekseer::Backend::TextureRef, Effekseer::Backend::TextureRef)’:
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:549:68: error: no matching function for call to ‘efk::BlitterGL::Blit(std::unique_ptr<EffekseerRendererGL::Shader>::pointer, std::unique_ptr<EffekseerRendererGL::VertexArray>::pointer, const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >&, std::nullptr_t, int, Effekseer::Backend::TextureRef&)’
  blitter.Blit(shader_.get(), vao_.get(), textures, nullptr, 0, dest);
                                                                    ^
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note: candidate: ‘void efk::BlitterGL::Blit(EffekseerRendererGL::Shader*, EffekseerRendererGL::VertexArray*, const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&, const void*, size_t, Effekseer::Backend::TextureRef, bool)’
 void BlitterGL::Blit(EffekseerRendererGL::Shader* shader,
      ^~~~~~~~~
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note:   no known conversion for argument 3 from ‘const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >’ to ‘const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&’
[11/24] Building CXX object Dev/Cpp/Test/CMakeFiles/Test.dir/Runtime/Performance.cpp.o
[12/24] Building CXX object Dev/Cpp/Test/CMakeFiles/Test.dir/Runtime/ResourceManager.cpp.o
[13/24] Building CXX object Examples/OpenGL/CMakeFiles/Example_OpenGL.dir/main.cpp.o
[14/24] Building CXX object Dev/Cpp/Test/CMakeFiles/Test.dir/Backend/Mesh.cpp.o

**Comment by durswd** [comment]
I tried to fix it.
Please check it.

https://github.com/effekseer/Effekseer/commit/a6bd50c2c2255fbd8e101b8c02508970cd5c17a7

**Comment by yangjianying** [comment]
../Dev/Cpp/Viewer/../EffekseerRendererGL/EffekseerRenderer/EffekseerRendererGL.GLExtension.h:171: warning: "GL_WRITE_ONLY" redefined
 #define GL_WRITE_ONLY 0x000088b9
 
In file included from /usr/include/GL/gl.h:2055,
                 from ../Dev/Cpp/Viewer/../EffekseerRendererGL/EffekseerRenderer/EffekseerRendererGL.GLExtension.h:56,
                 from ../Dev/Cpp/Viewer/../EffekseerRendererGL/EffekseerRenderer/GraphicsDevice.h:5,
                 from ../Dev/Cpp/Viewer/../EffekseerRendererGL/EffekseerRenderer/EffekseerRendererGL.DeviceObject.h:5,
                 from ../Dev/Cpp/Viewer/../EffekseerRendererGL/EffekseerRenderer/EffekseerRendererGL.IndexBuffer.h:8,
                 from ../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.h:5,
                 from ../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:8:
/usr/include/GL/glext.h:482: note: this is the location of the previous definition
 #define GL_WRITE_ONLY                     0x88B9
 
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp: In member function ‘virtual void efk::TonemapEffectGL::Render(Effekseer::Backend::TextureRef, Effekseer::Backend::TextureRef)’:
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:495:75: error: no matching function for call to ‘efk::BlitterGL::Blit(std::unique_ptr<EffekseerRendererGL::Shader>::pointer, std::unique_ptr<EffekseerRendererGL::VertexArray>::pointer, const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >&, std::nullptr_t, int, Effekseer::Backend::TextureRef&)’
   blitter.Blit(shaderCopy.get(), vaoCopy.get(), textures, nullptr, 0, dest);
                                                                           ^
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note: candidate: ‘void efk::BlitterGL::Blit(EffekseerRendererGL::Shader*, EffekseerRendererGL::VertexArray*, const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&, const void*, size_t, Effekseer::Backend::TextureRef, bool)’
 void BlitterGL::Blit(EffekseerRendererGL::Shader* shader,
      ^~~~~~~~~
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note:   no known conversion for argument 3 from ‘const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >’ to ‘const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&’
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:500:107: error: no matching function for call to ‘efk::BlitterGL::Blit(std::unique_ptr<EffekseerRendererGL::Shader>::pointer, std::unique_ptr<EffekseerRendererGL::VertexArray>::pointer, const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >&, const float [4], long unsigned int, Effekseer::Backend::TextureRef&)’
   blitter.Blit(shaderReinhard.get(), vaoReinhard.get(), textures, constantData, sizeof(constantData), dest);
                                                                                                           ^
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note: candidate: ‘void efk::BlitterGL::Blit(EffekseerRendererGL::Shader*, EffekseerRendererGL::VertexArray*, const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&, const void*, size_t, Effekseer::Backend::TextureRef, bool)’
 void BlitterGL::Blit(EffekseerRendererGL::Shader* shader,
      ^~~~~~~~~
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note:   no known conversion for argument 3 from ‘const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >’ to ‘const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&’
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp: In member function ‘virtual void efk::LinearToSRGBEffectGL::Render(Effekseer::Backend::TextureRef, Effekseer::Backend::TextureRef)’:
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:549:68: error: no matching function for call to ‘efk::BlitterGL::Blit(std::unique_ptr<EffekseerRendererGL::Shader>::pointer, std::unique_ptr<EffekseerRendererGL::VertexArray>::pointer, const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >&, std::nullptr_t, int, Effekseer::Backend::TextureRef&)’
  blitter.Blit(shader_.get(), vao_.get(), textures, nullptr, 0, dest);
                                                                    ^
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note: candidate: ‘void efk::BlitterGL::Blit(EffekseerRendererGL::Shader*, EffekseerRendererGL::VertexArray*, const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&, const void*, size_t, Effekseer::Backend::TextureRef, bool)’
 void BlitterGL::Blit(EffekseerRendererGL::Shader* shader,
      ^~~~~~~~~
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note:   no known conversion for argument 3 from ‘const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >’ to ‘const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&’
ninja: build stopped: subcommand failed.

**Comment by durswd** [comment]
I maybe fixed. Please retry. I'm sorry. I don't use ubuntu 16.04

**Comment by yangjianying** [comment]
/usr/include/GL/glext.h:482: note: this is the location of the previous definition
 #define GL_WRITE_ONLY                     0x88B9
 
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp: In member function ‘virtual void efk::LinearToSRGBEffectGL::Render(Effekseer::Backend::TextureRef, Effekseer::Backend::TextureRef)’:
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:549:68: error: no matching function for call to ‘efk::BlitterGL::Blit(std::unique_ptr<EffekseerRendererGL::Shader>::pointer, std::unique_ptr<EffekseerRendererGL::VertexArray>::pointer, const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >&, std::nullptr_t, int, Effekseer::Backend::TextureRef&)’
  blitter.Blit(shader_.get(), vao_.get(), textures, nullptr, 0, dest);
                                                                    ^
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note: candidate: ‘void efk::BlitterGL::Blit(EffekseerRendererGL::Shader*, EffekseerRendererGL::VertexArray*, const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&, const void*, size_t, Effekseer::Backend::TextureRef, bool)’
 void BlitterGL::Blit(EffekseerRendererGL::Shader* shader,
      ^~~~~~~~~
../Dev/Cpp/Viewer/Graphics/Platform/GL/efk.PostEffectsGL.cpp:189:6: note:   no known conversion for argument 3 from ‘const std::initializer_list<const Effekseer::RefPtr<Effekseer::Backend::Texture> >’ to ‘const std::vector<Effekseer::RefPtr<Effekseer::Backend::Texture> >&’
ninja: build stopped: subcommand failed.
cmake .. -G Ninja -DBUILD_VIEWER=ON -D BUILD_TEST=ON -D BUILD_EXAMPLES=ON
cmake --build . --config Release
Failed cmake --build . --config Release
Traceback (most recent call last):
  File "build.py", line 188, in <module>
    call('cmake --build . --config Release')
  File "build.py", line 21, in call
    raise Exception
Exception

**Comment by durswd** [comment]
I maybe fixed

**Comment by yangjianying** [comment]
it's ok now~
