### ISSUE TITLE
Feature Request : O3DE Plugin for effekseer.

### ISSUE THREAD

**Issue by WashedUpStudio** [effekseer/Effekseer#704]
Hi, I work with O3DE an open 3d engine that is used to make games, simulations, and cinematics, and I was wondering if getting a plugin for this engine is something that could be added to a to-do list to get support for an open source particle system. Thanks for any responses to this, and hope to see some discussion about it!

**Comment by durswd** [comment]
It needs more contributors. Contributors don't know O3DE at all.

**Comment by WashedUpStudio** [comment]
Ok that makes sense, I was just adding it since Effekseer supported a lot of engines already. It still could be possible, but the other way of making this work is someone knowing Effekseer that works on O3DE to make a gem (plugin) for Effekseer. Thanks for the response!
