### ISSUE TITLE
Archive Error iOS By For Unity ver1.61c

### ISSUE THREAD

**Issue by shusei918** [effekseer/Effekseer#707]
## 問題
URP環境下でForwardRendererに設定して開発しています。
iOSでビルドした後、Archiveを作成する際に以下のようなエラーが出て失敗してしまいます。

`bitcode bundle could not be generated because '/プロジェクトのパス/Libraries/Effekseer/Plugins/iOS/libEffekseerUnity.a(EffekseerPlugin.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64`

調べたところ、 #79 と同様のエラーのように思えます。
ご確認のほど、よろしくお願い致します。

## 環境
* Effekseer For Unity 1.61c
* Unity 2020.3.17
* URP 10.6.0

**Comment by durswd** [comment]
申し訳ございません。
cmakeにビルド方法を切り替えたときにオプションが抜け落ちたものと思われます。
実機テストまでは確認してたのですがArchiveを作成まではしてませんでした。
大急ぎで確認し、対応します。

**Comment by shusei918** [comment]
ありがとうございます。

**Comment by durswd** [comment]
ご迷惑をおかけして申し訳ございません。

https://github.com/effekseer/EffekseerForUnity/pull/68

このPRで作業中です。

**Comment by shusei918** [comment]
迅速な対応ありがとうございます。

**Comment by shusei918** [comment]
PRの内容でArchiveを作成できました。
ありがとうございました。

**Comment by durswd** [comment]
確認ありがとうございます。
1.61dとしてリリースしました。
