### ISSUE TITLE
 Effects of 50th or more nodes are not drawn

### ISSUE THREAD

**Issue by 123shaker** [effekseer/Effekseer#71]
ノードを追加していくと、ルートを含まず描画・非描画問わず50個目以降のノードの設定したエフェクトが描画されません。
これ以上描画させたい場合何か手段はありませんか？

**Comment by effekseer** [comment]
そこまでノードを追加したことはなかったです。
おそらく内部で確保したメモリの上限に引っかかっているため、数値を変えようと思います。
可能ならば、何らかの手段で描画されないノードを持つファイルを送っていただけると助かります。

**Comment by 123shaker** [comment]
返信ありがとうございます。
https://drive.google.com/file/d/0BwuEjG3BAA-yU3p4SHdNQVZZRXc/view?usp=sharing
こちらに該当ファイルをアップロードしました。「スパーク」以下のノードが描画されていません。確認お願いします。

**Comment by effekseer** [comment]
対応しました。Effekseerの最大ノード数の制限を撤廃しました。
We have abolished the limit of Effekseer's maximum node number.

https://github.com/effekseer/Effekseer/commit/5678f8372473cd04e771c3372b7946730d6dbd14
