### ISSUE TITLE
DX9 Rendering Glitch

### ISSUE THREAD

**Issue by HSNB** [effekseer/Effekseer#725]
"SetStreamSourceFreq" call is not properly handled. If the same EFK particle contains both nodes with and without instance data (I think models are without), then glitches on screen occur.

Make two changes:

replace

```
void RendererImplemented::DrawPolygon(int32_t vertexCount, int32_t indexCount)
{
	impl->drawcallCount++;
	impl->drawvertexCount += vertexCount;

	GetDevice()->DrawIndexedPrimitive(D3DPT_TRIANGLELIST, 0, 0, vertexCount, 0, indexCount / 3);
}
```

to

```
void RendererImplemented::DrawPolygon(int32_t vertexCount, int32_t indexCount)
{
	impl->drawcallCount++;
	impl->drawvertexCount += vertexCount;

	auto vb = static_cast<Backend::VertexBuffer*>(instancedVertexBuffer_.Get());
	GetDevice()->SetStreamSource(1, vb->GetBuffer(), 0, sizeof(float));
	GetDevice()->SetStreamSourceFreq(0, D3DSTREAMSOURCE_INDEXEDDATA | 1);
	GetDevice()->SetStreamSourceFreq(1, D3DSTREAMSOURCE_INSTANCEDATA | 1);

	GetDevice()->DrawIndexedPrimitive(D3DPT_TRIANGLELIST, 0, 0, vertexCount, 0, indexCount / 3);
}
```

And, in this function:

`bool RendererImplemented::EndRendering()`

Add:

```
	GetDevice()->SetStreamSourceFreq(0, 1);
	GetDevice()->SetStreamSourceFreq(1, 1);
```

Read information about SetStreamSourceFreq here:
https://docs.microsoft.com/en-us/windows/win32/direct3d9/efficiently-drawing-multiple-instances-of-geometry

![abc](https://user-images.githubusercontent.com/83901493/141333360-51405434-1b24-4539-9b22-480c63a2a3d3.png)

In "RendererImplemented::DrawPolygon" I put "GetDevice()->SetStreamSourceFreq(0, D3DSTREAMSOURCE_INDEXEDDATA | 1);" instead of "GetDevice()->SetStreamSourceFreq(0, 1);" because I believe the Effekseer shaders still expect instance data for 1 instance. It is some months ago that I fixed this bug so I can't remember but I think that was the reason.

**Comment by durswd** [comment]
I fixed it
https://github.com/effekseer/Effekseer/commit/4f152efe9d3317efde979de2f6e06130028d9ea2
