### ISSUE TITLE
Crash when opening file dialog

### ISSUE THREAD

**Issue by scribblemaniac** [effekseer/Effekseer#729]
I am trying to use Effekseer on Linux (Ubuntu 21.10) and I have successfully compiled it and can run the program. However when I try to do actions which would open the file explorer such as saving a project or loading a texture, the program crashes. This is the output from the program:
```
(Effekseer:1221704): Gtk-WARNING **: 00:41:14.820: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Fatal error reading PNG image file: Invalid IHDR data (gdk-pixbuf-error-quark, 0)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Fatal error reading PNG image file: Invalid IHDR data (gdk-pixbuf-error-quark, 0)
Aborted (core dumped)
```

The image at `/usr/share/icons/Adwaita/16x16/status/image-missing.png` exists and seems to be a valid image. I've updated the mime and gtk-pixbuf caches. I've searched for this issue and I haven't found any way to fix this. I found some information that suggests that it could be an issue with libpng linking. I have version 1.6.37-3build4 installed, but I see a different version is being built for this program. Could that be the issue? Or does anyone have any other ideas? I have not encountered this issue with any other applications.

**Comment by durswd** [comment]
It is weird and I cannot reproduce it.
The bug is difficult for me.

**Comment by scribblemaniac** [comment]
Here, I have created [this Dockerfile](https://github.com/effekseer/Effekseer/files/7630183/Dockerfile.zip) to try and reproduce the issue, and it's exactly the same result for me. You will need to connect to VNC on port 5900 of the container after building and running this to try to save the project and trigger the crash.

By changing the Dockerfile, I have gathered an additional piece of information that may be helpful: this issue happens with Ubuntu 21.10 but not Ubuntu 20.04 or 21.04.

**Comment by durswd** [comment]
Thank you for your information.
The dialog is shown with this library (https://github.com/mlabbe/nativefiledialog)

In the next step, it needs to check whether the library run on 21.10

**Comment by scribblemaniac** [comment]
Just built it and [the tests](https://github.com/mlabbe/nativefiledialog/tree/master/test) all run without issue.

**Comment by scribblemaniac** [comment]
Update: I changed [this line](https://github.com/effekseer/Effekseer/blob/master/Dev/Cpp/3rdParty/CMakeLists.txt#L52) to:
```
list(APPEND nfd_src nativefiledialog/src/nfd_zenity.c)
```
to use the alternative Zenity backend, and now Effekseer is working. However the nfd tests I ran worked with the GTK backend so in theory they should both work.

**Comment by durswd** [comment]
Thank you.
It is weird...
