### ISSUE TITLE
Running particles on cocos, performance issues?

### ISSUE THREAD

**Issue by jiangjian0402** [effekseer/Effekseer#736]
I found a problem in cocos. When I create a node and emit particles, when the number of vertices reaches about 20000, the frame rate will be reduced from 60 to 30. What is the reason for this?

**Comment by durswd** [comment]
Which effect do you play? If the effect is much complicated, it is normal.

**Comment by jiangjian0402** [comment]
Thank you for your reply I just added a node node, set the number of particles to 10000 and the particle survival time to 10000, and found that when the number of vertices exceeded about 10000, the performance began to decline. Do you know what mechanism causes this? I can investigate it because I want to apply this particle system to the vehicle system.

**Comment by durswd** [comment]
It seem that OpenGL driver problem

**Comment by jiangjian0402** [comment]
Thank you. I may know some reasons. In addition, there is another problem. The effect of putting Laser03.efk on an Android phone is different from that of windows. Why is this?
![1640613926245](https://user-images.githubusercontent.com/44841771/147479436-c0d263e5-5d99-436b-916a-494ac63554f4.jpg)
![image](https://user-images.githubusercontent.com/44841771/147479556-8ca31308-81ff-47fe-a563-f86e12234d3c.png)

**Comment by durswd** [comment]
I will check...

**Comment by durswd** [comment]
It may causes by this line
https://github.com/effekseer/EffekseerForCocos2d-x/blob/master/Players/Cocos2d-x_v4/EffekseerForCocos2d-x/EffekseerForCocos2d-x.cpp#L784

**Comment by jiangjian0402** [comment]
I set it, but the effect is still the same. It can't be displayed like window.

**Comment by jiangjian0402** [comment]
Sorry, it's my carelessness. Now I've solved it. Thank you for your support
