### ISSUE TITLE
Archive Error IOS By For Unity 1.22

### ISSUE THREAD

**Issue by harayuu9** [effekseer/Effekseer#79]
Unity 5.6.0f3 Effekseer1.22 で開発しています。
Unityの方でIOSbuildをかけてXcodeで読み込むと実機テストは問題なく出来るのですが、
Archive化をすると以下のリンクエラーが出てしまいます。

ld: bitcode bundle could not be generated because 'プロジェクトディレクトリまでのパス/Libraries/Plugins/iOS/libEffekseerUnity.a(EffekseerPluginCommon.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64

libEffekseerUnity.aのほうにbitcode情報がついてないように見えます。
対応の方をよろしくお願いします。

**Comment by effekseer** [comment]
了解しました。確認しますので少々お待ちください。

**Comment by effekseer** [comment]
もしかしたら、1.3beta1では治っているかもしれないので、そちらも確認してみてください。

**Comment by harayuu9** [comment]
1.3beta1試してみましたが変わりませんでした。

**Comment by effekseer** [comment]
問題確認しました。
とりあえず、リポジトリには修正版をあげました。
急ぎでなければ1.3beta2をお待ちください。

**Comment by effekseer** [comment]
とりあえず、Win、Mac、iOS、Androidのみ対応の最新パッケージです。
おそらくこのバージョンで治っているはずです。
http://effekseer.sakura.ne.jp/Releases/EffekseerForUnity170618.zip

**Comment by harayuu9** [comment]
わざわざありがとうございます。Archiveも成功しました。

**Comment by effekseer** [comment]
いえいえ。このissueは1.3をリリースした後に閉じます。

It's my pleasure. This issue closes after releasing 1.3.
