### ISSUE TITLE
Visual studio 2017での不具合について

### ISSUE THREAD

**Issue by togetg** [effekseer/Effekseer#82]
http://qiita.com/CdecPGL/items/3291936706e1be780b1e
以上のサイトに載っている修正をしないとvs2017で正常に使用できない不具合を解消して頂きたいです。

**Comment by effekseer** [comment]
リポジトリ版やベータ版では修正済みです。
正式リリースをお待ちください。

**Comment by effekseer** [comment]
とりあえず、こちらを試していただけないでしょうか？

http://effekseer.sakura.ne.jp/Releases/EffekseerForDXLib170927.zip
