### ISSUE TITLE
dxlib版のDrawHandleを用いた描画について（解決）

### ISSUE THREAD

**Issue by kurikinton9999** [effekseer/Effekseer#83]
いつもお世話になっております。
EffekseerforDxlibにてDrawHandleを用いた描画を行った際本来の描画結果が得られない現象を確認いたしました。

処理順序は
インスタンス取得（3D）
↓
エフェクト更新（UpdateEffekseer3D）
↓
DrawHandle

といった感じです。
試しにUpdateHandleを用いてやっても見ましたが結果は変わりませんでした。
ご確認お願いいたします。

**Comment by effekseer** [comment]
報告ありがとうございます。
可能なら、それを再現できる最短コードを頂けると助かります。

**Comment by effekseer** [comment]
DXLib版のコードをみましたが、
DrawEffekseer2D_Begin　にあたる操作を3Dで行う
DrawEffekseer2D_Draw　にあたる操作を3Dで行う
DrawEffekseer2D_End　にあたる操作を3Dで行う
としないとだめなようです。

**Comment by kurikinton9999** [comment]
EffekseeerForDxlibのサンプルをいじったものですが現象を確認したソースをアップロードしておきました。
http://firestorage.jp/download/15da295a31a9cf265c8f435ed8355fe9221685ee

Begin⇒Endは描いていたのですがこれであってるか分からないので間違っていたら申し訳ないです…。

**Comment by effekseer** [comment]
GetEffekseer3DRendererでレンダラーを取得して、

	// 頂点バッファに溜まった頂点データを吐き出す。
	RenderVertex();

	// エフェクトの描画開始処理を行う。
	g_renderer3d->BeginRendering();

	// エフェクトの描画を行う。
	g_manager3d->DrawHandle(xxx);

	// エフェクトの描画終了処理を行う。
	g_renderer3d->EndRendering();

	// DXライブラリの設定を戻す。
	RefreshDxLibDirect3DSetting();

と記述する必要があります。

**Comment by kurikinton9999** [comment]
教えていただいたとおりにやったところ解決いたしました。
お手数おかけして申し訳ありませんでした・・・！

**Comment by effekseer** [comment]
RC1にて
DrawEffekseer3D_Begin
DrawEffekseer3D_Draw
DrawEffekseer3D_End
をそれぞれ追加しました
