### ISSUE TITLE
how to cancel shine

### ISSUE THREAD

**Issue by trycatchx** [effekseer/Effekseer#842]
Particles overlap, how to cancel shine

eg:
![image](https://user-images.githubusercontent.com/6050250/174763245-bf9022ee-9b0d-4aa3-8a94-cb9c5d2565de.png)

**Comment by trycatchx** [comment]
@durswd  How to control the Emissive Scale ，and do not shine? Is there any relevant documentation, I would like to know about it，thx！

**Comment by durswd** [comment]
https://effekseer.github.io/Help_Tool/en/ToolReference/rendererCommon.html#emmisive-scaling

**Comment by trycatchx** [comment]
thx，i got it
