### ISSUE TITLE
android - how to make  Effekseer backgroud color transparent

### ISSUE THREAD

**Issue by trycatchx** [effekseer/Effekseer#852]
how to make  Effekseer backgroud color transparent.
 
 I write this code to make my GLSurfaceView transparent :
 ```
       setEGLConfigChooser(8,8,8,8,16,0);
       setRenderer(Renderer());
       getHolder().setFormat(PixelFormat.TRANSLUCENT)
       setRenderMode(GLSurfaceView.RENDERMODE_WHEN_DIRTY)
       setZOrderOnTop(true);
 ```
 But I still get black background 。like this :
 
 
![image](https://user-images.githubusercontent.com/6050250/176426407-4bb849bc-2271-467d-a1ed-ec6427cdeda9.png)

**Comment by durswd** [comment]
Effekseer simply draws on the background. I don't know why, but I think the background is not transparent correctly.

**Comment by trycatchx** [comment]
@durswd  ok, thx for your reply ,I keep looking for the problem in my code
