### ISSUE TITLE
The particle color has changed

### ISSUE THREAD

**Issue by trycatchx** [effekseer/Effekseer#853]
Hi ! I set the following line of code. Finally the background becomes transparent, but the particle color changes to black. what is wrong？
```       
 glClearColor(0.0f, 0.0f, 0.0f, 0.0f);
```

![image](https://user-images.githubusercontent.com/6050250/176624588-e688f26d-c0b5-4315-abbb-59bd2d5423ab.png)

The effect I expect is for the background to be transparent，and particle color is correct. 

Where should I work?

**Comment by durswd** [comment]
Please try to call  glClearColor(1.0f, 1.0f, 1.0f, 0.0f);

But it is difficult to render effects perfectly on transparent background.
It is better to draw effects to rendering targets directly.

**Comment by trycatchx** [comment]
by the way ,i change  Blend to Add  for xxx.efkefc mode , I get effect like the following : 
![image](https://user-images.githubusercontent.com/6050250/176675349-465c95a2-35e1-4db6-9646-bf9a5a8dacf3.png)

Add （加算） mode ： the color of effect is correct, but it shine! 
Blend (透明)   mode :  the color of effect is wrong。

I want the color to be correct and transparent in blend mode, what should I do? thx！

**Comment by trycatchx** [comment]
> 

it is no work , I call glClearColor(1.0f, 1.0f, 1.0f, 0.0f);  the background change to white（opaque）

**Comment by trycatchx** [comment]
ok， thanks for your reply！
