### ISSUE TITLE
Broken flipbook frame blending

### ISSUE THREAD

**Issue by abvadabra** [effekseer/Effekseer#860]
When flipbook frame blending is enabled something goes wrong with interpolation of frames which are located on different rows of the spritesheet. Seems to be reproducible both in 1.6b build and in master branch.
 
Effekseer package in which issue can be observed: [BrokenFlipbook.zip](https://github.com/effekseer/Effekseer/files/9103029/BrokenFlipbook.zip)

Steps to reproduce:

- Import attached efkpkg file in editor compiled from master branch
- Play the effect
- Observe visual artefacts of frames interpolation

![EffekseerBrokenFlipbook](https://user-images.githubusercontent.com/8457835/178755777-c3b3aac0-c938-49ac-a317-b5dcbd3240d1.gif)

**Comment by durswd** [comment]
- Work around.
Please change the number of flips from (8/6) to (8/8)
I will fix it in 1.7

**Comment by durswd** [comment]
I fixed it
https://github.com/effekseer/Effekseer/pull/864

**Comment by abvadabra** [comment]
Thank you!
