### ISSUE TITLE
EffekseerとEffekseerforDxlibを用いた際のエラーについて

### ISSUE THREAD

**Issue by kurikinton9999** [effekseer/Effekseer#87]
いつもお世話になっております。
前回は本当にありがとうございました。

最新バージョンのEffekseerとEffekseerForDxlibについて気づいたことがあったのでご報告させていただきます。

古いバージョンのEffekseerForDxlibを用いた際に、最新版Effekseerで吐いたefkファイルを読み込もうとするとエラーが出ることを確認いたしました。
念のためEffekseerForDxlibを最新バージョンにし実行したところ、古いバージョンで吐かれたefkファイルを読み込む際にエラー、
最新バージョンのEffekseerを用いて吐いたefkファイルでもエラーが出ることを確認しています。

最新版EffekseerForDxlibについているサンプルでもエラーが出ることを確認いたしました。
ご確認お願いいたします。

**Comment by effekseer** [comment]
おはようございます。
いつも使用していただきありがとうございます。

とりあえず、最新版のEffekseerから出力したefkファイルを最新版のEffekseerForDXLibで再生したところ、普通に再生できてしまったので、今回再生に使用したefkファイルおよびefkprojファイルいただけないでしょうか？

よろしくお願いします。

**Comment by kurikinton9999** [comment]
了解しました。
エフェクトファイルはこちらになります
【http://firestorage.jp/download/5521f1f730c1bd7a4301255b8c1bf795017b3be6】

エラー・・・というより例外？といった方が良いのでしょうか、内容も念のため、
「Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.」

**Comment by effekseer** [comment]
ありがとうございます。
それらのファイルを最新のEffekseerForDXLibで再生してみたのですが、現在エラーが出ておりません。
もうちょっと調査してみますが、エラー出るプロジェクトごと送っていただけると助かる可能性もあります。

**Comment by effekseer** [comment]
EffekseerForDXLibについては、サンプルのファイル名を差し替えて検証しています。

**Comment by effekseer** [comment]
不具合があることを確認し、最新のリポジトリ版では修正済みであることを確認しました。
1.30をお待ちください。
ちなみに原因はモデルなので、RC2で再度、efkmdlファイルを生成すれば動きます。

**Comment by kurikinton9999** [comment]
確認が遅れてしまいすみません。
モデルが原因でしたか・・・しかし先の最新版のサンプルをDLした際そのままサンプルに同梱されているefkファイルをプログラムを実行し再生した際にもRun-Time Check Failure #0 - The value of ESP was not properly saved ~~のエラーが出てきました。

VS2013での実行がいけないのか自身の環境が悪いのかといった感じです…。

**Comment by effekseer** [comment]
プログラム自体もサンプルのそのままでしょうか？

**Comment by effekseer** [comment]
いや、確かに2013だと発生しました。調査してみます。

**Comment by kurikinton9999** [comment]
はい、変えておりません。
お手数おかけして申し訳ないです、よろしくお願いいたします…！

**Comment by effekseer** [comment]
http://effekseer.sakura.ne.jp/Releases/EffekseerForDXLib171029.zip
修正してみましたがこれでいかがでしょうか

**Comment by kurikinton9999** [comment]
確認いたしました
無事最新版で吐いたefkファイルのエフェクトも再生でき、現状の物も問題なく読み込み・再生されました

お早い対応本当にありがとうございました・・・！
