### ISSUE TITLE
dead code in effekseer.client.cpp

### ISSUE THREAD

**Issue by mmyjona** [effekseer/Effekseer#89]
https://github.com/effekseer/Effekseer/blob/master/Dev/Cpp/Effekseer/Effekseer/Effekseer.Client.cpp#L116

> 	/* ソケット生成 */
	EfkSocket socket_ = Socket::GenSocket();
	if ( socket_ == InvalidSocket )
	{
		if ( socket_ != InvalidSocket ) Socket::Close( socket_ );
		return false;
	}

**Comment by effekseer** [comment]
Thank you .
This is my mistake.
I will fix it.

**Comment by effekseer** [comment]
I fixed it.
https://github.com/effekseer/Effekseer/commit/a03bc798d30dcfe6eace7a79a8cf8cdae1cd21e8
