### ISSUE TITLE
Unityでの、Time.timeScale = 0 で再生する方法

### ISSUE THREAD

**Issue by lsklista** [effekseer/Effekseer#94]
UnityでEffekseerで作ったエフェクトを再生する際、
エフェクトの再生速度がTime.timeScaleに依存するのはいいのですが、
一部のエフェクトは、Time.timeScaleに依存しないで再生できるようにしたいです。
どうにかしてTime.timeScale = 0の時でも通常の速度で再生できるようにする方法はないでしょうか？

よろしくお願い致します。

■動作環境
Unity                           2017.2.0f3
Effekseer                     1.32
Effekseer For Unity     1.30

**Comment by effekseer** [comment]
ForUnityを開発している人に確認してみます。

**Comment by kou-yeung** [comment]
自前実装が必要ですが、EffekseerHandle.UpdateHandle(...) を使えば実現できます。

// 再生したエフェクトのハンドルを保持する
EffekseerHandle handle = EffekseerSystem.PlayEffect(currentEffectName, Vector3.zero);

// ハンドルを更新する：EffekseerSystem.cs Line.462~を参考します
handle.UpdateHandle(Time.unscaledDeltaTime * 60);

**Comment by durswd** [comment]
今更ですが実装しました。
