### ISSUE TITLE
最新バージョン(1.70e)のブランチを取得し、UE 5.2で起動すると再インポート出来ない

### ISSUE THREAD

**Issue by R-Inoue-CR** [effekseer/Effekseer#942]
いつもお世話になっております。
この度は表題の件を確認させていただきたいのですが、よろしいでしょうか。

空のプロジェクトを作成したのち、Switch Unreal Engine Version...で5.2を選択してエディタを起動します。
そしてEffekseerData・EffekseerModelDataの再インポートが出来ないことを確認致しました。

Engine\Source\Editor\AssetDefinition\Private\AssetDefinition.cpp
上記ファイルの以下項目が原因だと思われます。
UAssetDefinition::GetSourceFilesの
if (InAsset.GetTagValue(UObject::SourceFileTagName(), SourceFileTagData))

再インポートできるアセットは右クリックでこちらのif文が通っておりました。

既知でしたら申し訳ないですが、暫定的対処法をご教示いただけますと幸いです。
また次回アップデートで対応予定などの情報もございましたら、ありがたいです。

**Comment by durswd** [comment]
報告ありがとうございます。
週末に確認して対応します。

**Comment by durswd** [comment]
https://github.com/effekseer/EffekseerForUE/commit/2cae4e4de3af568d81084d47a55d407f1eaedd53
このcommitで修正しました。
試し見ていただけると助かります。

**Comment by R-Inoue-CR** [comment]
インポート済みアセット欄使用可能の確認致しました。
ご対応いただきありがとうございました。
