### ISSUE TITLE
DXライブラリ側で非同期読み込みを設定した場合、LoadEffekseerEffectでアクセス違反を起こします

### ISSUE THREAD

**Issue by rumichi2210** [effekseer/Effekseer#958]
Effekseer for DXライブラリにて、SetUseASyncLoadFlag(TRUE)で非同期読み込みを行っているときに、
LoadEffekseerEffect()を実行した場合、正常に描画されない、またはアクセス違反が発生します
なにか解決法はありますでしょうか？

実行環境
Effekseer for DXライブラリ (1.70e,3.24b)

Effekseer for DXライブラリのサンプルにSetUseASyncLoadFlag(TRUE)を設定する。
0x00007FF6FAA23ED1 で例外がスローされました (Sample_VS2022.exe 内): 0xC0000005: 場所 0x0000000000000000 の読み取り中にアクセス違反が発生しました

**Comment by durswd** [comment]
現状は読み込むときだけSetUseASyncLoadFlagを無効化するしかありません。

**Comment by rumichi2210** [comment]
了解しました。
ご回答頂きありがとうございます。
