### ISSUE TITLE
EffekseerForUEの最新版(1.70f)でEffekseerEmitterComponentのTranslucencySortPriorityが機能していない

### ISSUE THREAD

**Issue by R-Inoue-CR** [effekseer/Effekseer#964]
いつもお世話になっております。
この度は表題の件を確認させていただきたいのですが、よろしいでしょうか。

最新版を取得し、Actorのブループリントを作成しました。
そのBPにEffekseerEmitterを2つ追加し、TranslucencySortPriorityを設定しましたが描画順が変わりませんでした。

プレイボタンを押す前のView画面だと機能しているように見えました。

こちら既知の不具合でしたら申し訳ないですが、こちらの対応予定等ありますでしょうか？
もしありましたら、バージョン等ご教示いただけますと幸いです。

**Comment by durswd** [comment]
報告ありがとうございます。
既知の不具合ではありません。
確認してみます。

**Comment by durswd** [comment]
確認しましたが、そもそもTranslucencySortPriorityは実装されておらず、後ろから前に順番に描画するようになっています。一方で描画順を制御する方法は検討してみます。

**Comment by R-Inoue-CR** [comment]
後ろから前に順番に描画する処理は、Effekseer.Manager.hのDrawParameter::IsSortingEffectsEnabled関連の処理でしょうか？
現状の機能に併せてUEのデフォルト機能であるTranslucencySortPriorityも対応できるような実装が出来ればと思いご連絡させていただきました。

ご検討のうえご連絡頂けると幸いです。どうぞよろしくお願い致します。

**Comment by durswd** [comment]
調べた限り、現状のUEのTranslucencySortPriorityに対応はある程度の工数が必要という認識になりました。
現在のRendererはComponent1つの中で完結していますが、TranslucencySortPriorityはコンポーネントごとのパラメーターなので描画を複数のコンポーネント（もしくは内部でそれ相応の描画命令に分割）に描画する必要があります。

Effekseer独自でTranslucencySortPriority相当の機能を追加するのは難しくはないのですが、それでは問題がありますでしょうか？

**Comment by R-Inoue-CR** [comment]
回答遅れてしまい申し訳ありません。
もし仮に対応してくださるとすると、UE Default機能ですと幸いです。

GPUパーティクルなどを使用したいので別のエミッタコンポーネントと併用している状況なので嚙み合わせが良い、「現状のUEのTranslucencySortPriorityに対応」の方が好ましいです。

工数から考え不都合があるようでしたら、対応は無しで結構です。

**Comment by durswd** [comment]
少々考えますので数日お待ちください。

**Comment by durswd** [comment]
開発に着手しました。上手く予定通りの挙動をするなら1週間程度かかる見込みです。

**Comment by durswd** [comment]
このブランチで開発中です。
不具合はやまほどありますが最低限動作しました。

https://github.com/effekseer/EffekseerForUE/tree/translucency_sort_priority

**Comment by R-Inoue-CR** [comment]
ご対応ありがとうございます。
お手数おかけしますがよろしくお願いいたします。

**Comment by durswd** [comment]
上記ブランチでおおよそ不具合修正も終わり、動くようになったのですが一度試していただけないでしょうか？

**Comment by R-Inoue-CR** [comment]
承知いたしました。
確認致します。

**Comment by R-Inoue-CR** [comment]
確認いたしました。
理想通りの挙動となっております。ご対応ありがとうございました！

**Comment by R-Inoue-CR** [comment]
いつもお世話になっております。
こちらで行って頂いた変更を、マスターブランチへのマージすることは考えられていますでしょうか？

この対応は試験的なもので本ブランチへの適応は現状ない形でしょうか。

**Comment by durswd** [comment]
忘れていただけなのでマージしました。

**Comment by R-Inoue-CR** [comment]
ここまでのご対応ありがとうございました！

**Comment by R-Inoue-CR** [comment]
こちら確認いたしました、問題ありませんでした。

気になった点が一点あります。
EffekseerSystem::Init()でModelRendererの作成がされてないように思いますので、ご確認お願いします。
以上ですので本件クローズで問題ありません。
